---
title: "Overview"
---

---

The following lists contain all manuals, examples, and additional material for the **ExESS** documentation and software.

## Essentials

* [Student Thesis: On-Boarding Checklist](/manuals/essentials/onboarding_checklist/index.qmd) is recommended for all new students to get started with their university thesis and working with the **ExESS** package 
* [Julia Programming Language: Links & Resources](/manuals/essentials/julia_links/index.qmd) contains links to the most important resources for learning the Julia programming language, including a subset of important packages for scientific computing, used in and together with the **ExESS** package
* [Git Essentials](/manuals/essentials/git_essentials/index.qmd) lists some external links to resources for learning the Git version control system
* [ExESS Package Installation](/manuals/essentials/package_installation/index.qmd) describes how to install the **ExESS** package on your computer


## Code Examples

* [Trajectory Calculation](/manuals/code_examples/example_trajectory_01/index.qmd) provides an example of a purely ballistic trajectory calculation
* [Comparison of Landing Position Calculations: 2D vs. 3D](/manuals/code_examples/2d_3d_landing_position_comparison/index.qmd) 


## Exercises

---