project:
  type: website
  output-dir: docs

jupyter: julia-1.9

bibliography: "../asmolka_library/main.bib"

website:
  title: "ExESS"
  favicon: "/resources/logo/exess_logo.png"
  search: true
  navbar:
    background: primary
    logo: /resources/logo/exess_logo.svg
    logo-href: /index.qmd
    left:
      - text: "Home"
        href: index.qmd
      - text: "Documentation"
        href: documentation/documentation.qmd
      - text: "Wiki"
        href: src/wiki.qmd
      - text: "Manual"
        href: src/manual.qmd
      - text: "API"
        href: api/api.qmd

  sidebar:
    - title: "Home"
      style: docked
      background: light
      contents:
        - text: "Home"
          href: index.qmd

    - title: "Documentation"
      style: docked
      background: light
      collapse-level: 3
      contents:
        - text: "Documentation"
          href: documentation/documentation.qmd
        - text: "1 - Introduction"
          href: documentation/introduction.qmd
        - section: "2 - Mathematics, Numerics, and Computational Foundations"
          href: documentation/math_num_comp.qmd
          contents:
            - section: 
              text: "2.1 - Coordinate Systems"
              href: documentation/math_num_comp/coordinate_systems.qmd
              contents:
                - documentation/math_num_comp/coordinate_systems/cartesian_spherical_coordinates.qmd
                - documentation/math_num_comp/coordinate_systems/spacial_differentials.qmd
                - documentation/math_num_comp/coordinate_systems/temporal_differentials.qmd
            - section:
              text: "2.2 - Numerical Grids"
              href: documentation/math_num_comp/numerical_grids.qmd
              contents:
                - documentation/math_num_comp/numerical_grids/global_structured_grids.qmd

    - title: "Wiki"
      style: docked
      background: light
      contents:
        - src/wiki.qmd

    - title: "Manual"
      style: docked
      background: light
      contents:
        - src/manual.qmd

    - title: "API"
      style: docked
      background: light
      contents:
        - text: ExESS API
          href: api/api.qmd
        - section: "Base"
          contents:
            - text: "Constants"
              href: api/base/constants.qmd
            - text: "Coordinate Systems"
              href: api/base/cs.qmd

format:
  html:
    theme: [flatly, _mystyle.scss]
    css: styles.css
    code-link: true
    html-math-method: 
      method: mathjax
    extra_dependencies: ["siunitx"]
    include-in-header: 
      - resources/mathjax.html
