project:
  type: website
  output-dir: docs

jupyter: julia-1.9

bibliography: "../asmolka_library/main.bib"
csl: apa.csl

website:
  site-url: https://smolkaa.github.io
  title: "ExESS"
  repo-url: https://github.com/Smolkaa/smolkaa.github.io
  repo-actions: [edit]
  favicon: "/resources/logo/exess_logo.png"
  search: true
  page-navigation: true

  navbar:
    background: primary
    pinned: true
    logo: /resources/logo/exess_logo.svg
    logo-href: /index.qmd
    left:
      - text: "{{< fa house >}} Home"
        href: index.qmd
      - text: "{{< fa book >}} Documentation"
        href: documentation/documentation.qmd
      - text: "{{< fa book-open-reader >}} Manuals"
        href: manuals/manuals.qmd
      - text: "{{< fa code >}} Code"
        href: api/api.qmd
      - text: "{{< fa bookmark >}} Bibliography"
        href: bibliography/bibliography.qmd
    right:
      - icon: github
        href: https://github.com/Smolkaa

  sidebar:
    - title: "Home"
      border: true
      collapse-level: 2
      pinned: true
      style: "floating"
      contents:
        - text: "Home"
          href: index.qmd

    - title: "Documentation"
      contents:
        - text: "Home"
          href: documentation/documentation.qmd
        - documentation/acronyms.qmd
        - text: "Introduction"
          href: documentation/introduction.qmd
        - "---"
        - section: "Mathematics, Numerics, and Computational Foundations"
          contents:
            - documentation/math_num_comp/coordinate_systems.qmd
            - documentation/math_num_comp/numerical_grids.qmd
            - documentation/math_num_comp/statistics.qmd
        - "---"
        - section: "Fundamentals"
          contents:
            - documentation/fundamentals/moon.qmd
            - documentation/fundamentals/velocity_distributions.qmd
            - documentation/fundamentals/gravitational_potential.qmd
        - "---"
        - section: "Particle Trajectories"
          contents:
            - documentation/trajectories/orbital_mechanics_functions.qmd
            - documentation/trajectories/2d_landing_position.qmd
        - "---"
        - section: "Planetary Measurements and Data"
          contents: 
            - documentation/planetary_measurements/lunar_exosphere_densities.qmd
        

    - title: "Manuals"
      contents:
        - text: "Overview"
          href: manuals/manuals.qmd

    - title: "Code"
      contents:
        - text: "Home"
          href: api/api.qmd
        - section: "Base"
          contents:
            - api/base/constants.qmd
            - api/base/cs.qmd
            - api/base/distributions.qmd
        - section: "Numerical Grids"
          contents:
            - api/grids/global_structured_2d_grids.qmd
            - api/grids/utility.qmd

    - title: "Bibliography"
      contents:
        - text: "Overview"
          href: bibliography/bibliography.qmd

format:
  html:
    anchor-sections: true  
    code-copy: true
    code-link: true
    css: styles.css
    filters:
      - lightbox
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 400px
    html-math-method: mathjax
    include-in-header: 
      - resources/mathjax.html
    lightbox: auto
    link-external-newwindow: true
    theme: [flatly, _mystyle.scss]
    title-block-style: default
    toc: true

