project:
  type: website
  output-dir: docs

jupyter: julia-1.9

bibliography: "../asmolka_library/main.bib"
csl: _apa.csl

website:
  # site-url: https://smolkaa.github.io
  title: "ExESS"
  repo-url: https://github.com/Smolkaa/smolkaa.github.io
  # repo-actions: [edit]
  favicon: "/resources/logo/exess_logo.png"
  search: true
  page-navigation: true

  navbar:
    background: dark
    logo: /resources/logo/exess_logo_dark.svg
    left:
      - text: "Home"
        href: index.qmd
        icon: house
      - text: "Documentation"
        href: documentation/documentation.qmd
        icon: book
      - text: "Code"
        href: api/api.qmd
        icon: journal-code
    right:
      - icon: github
        href: https://github.com/Smolkaa

  sidebar:
    - title: "Home"
      # border: true
      # logo: /resources/logo/exess_logo_dark.svg
      logo: /resources/logo/exess_logo.svg
      collapse-level: 1
      # style: "docked"
      # background: secondary
      background: white
      # contents:
        # - text: "Home"
          # href: index.qmd
      #   - section: "Additional Resources"
      #     contents:
      #       - additionals/essentials/julia_links/index.qmd
      #       - additionals/essentials/package_installation/index.qmd
      #       - additionals/code_examples/mc_simulation/index.qmd
      #       # - guide/code_examples/2d_3d_landing_position_comparison/index.qmd
      #   - text: License
      #     href: LICENSE.md



    - title: "Documentation"
      contents:
        - documentation/documentation.qmd
        - documentation/acronyms.qmd
        - documentation/introduction/introduction.qmd
        - section: "2. Fundamentals"
          contents:
            - documentation/fundamentals/coordinate_systems.qmd
            - documentation/fundamentals/numerical_grids.qmd
            - "2.3 ODEs and Numerical Solvers"
            - documentation/fundamentals/stats_mc.qmd
            - documentation/fundamentals/moon.qmd
            - documentation/fundamentals/properties_data.qmd
        - section: "3. Drivers of Exospheres"
          contents:
            - documentation/drivers/solar_wind.qmd
            - documentation/drivers/thermal_sorption.qmd
            - documentation/drivers/photoreactions.qmd
            - "Photon and Electron Stimulated Desorption"
            - "Sputtering"
            - "Micrometeoroid Impact Vaporization"
        - section: "4. Exospheres: Particle Trajectories"
          contents:
            - documentation/trajectories/ballistic_trajectories.qmd
            - documentation/trajectories/non-ballistic_trajectories.qmd
        - section: "5. Surfaces: Planetary Regolith"
          contents:
            - documentation/regolith/composition.qmd
            - "5.1 Physical and Chemical Properties"
        - section: "6. Particle-Surface Interactions"
          contents:
            - documentation/surface_interaction/physical_chemistry.qmd
        - section: "7. Investigation of Model Influences"
          contents:
            - "7.1 Topography and Roughness"
            - "7.2 Transient"
            - "7.3 Ion Exosphere and Recycling"
        - section: "8. Lunar Water Exosphere Simulation"
          contents:
            - documentation/lunar_water_exosphere/conversion_model.qmd
        - section: 9. Outlook and Conclusion
          contents:
            - "9.X Other Exospheres in The Solar System"
        - section: "Appendix"


    - title: "Code"
      contents:
        - text: "Home"
          href: api/api.qmd
        - section: "Base"
          contents:
            - api/base/constants.qmd
            - api/base/cs.qmd
            - api/base/distributions.qmd
            - api/base/utility.qmd
        - section: "Exospheres"
          contents:
            - api/exospheres/trajectory.qmd
            - api/exospheres/landing_position.qmd
            - api/exospheres/utility.qmd
        - section: "Numerical Grids"
          contents:
            - api/grids/global_structured_2d_grids.qmd
            - api/grids/global_structured_3d_grids.qmd
            - api/grids/local_structured_3d_grids.qmd
            - api/grids/utility.qmd
        - section: "Surfaces"
          contents:
            - api/surfaces/temperature.qmd

format:
  html:
    anchor-sections: true  
    code-copy: true
    code-link: true
    css: _styles.css
    grid:
      sidebar-width: 350px
      # body-width: 1000px
      body-width: 1200px
      # margin-width: 300px
      margin-width: 0px
    html-math-method: mathjax
    include-in-header: 
      - resources/mathjax.html
      - resources/head.html
    lightbox: auto
    link-external-newwindow: true
    theme:
      - lumen
      - mystyle.scss
    title-block-style: default
    toc: false
    # toc-title: "{{< meta title >}}"
    toc-title: "Table of Contents"
    toc-location: body
    toc-depth: 2

