project:
  type: website
  output-dir: docs

jupyter: julia-1.9

bibliography: "../asmolka_library/main.bib"
csl: _apa.csl

website:
  # site-url: https://smolkaa.github.io
  title: "**ExESS**"
  repo-url: https://github.com/Smolkaa/smolkaa.github.io
  repo-actions: [edit]
  favicon: "/resources/logo/exess_logo.png"
  search: true
  page-navigation: true

  navbar:
    background: primary
    pinned: true
    # logo: /resources/logo/exess_logo.svg
    logo-href: /index.qmd
    left:
      - text: "{{< fa house >}} Home"
        href: index.qmd
      - text: "{{< fa book >}} Documentation"
        href: documentation/documentation.qmd
      - text: "{{< fa bookmark >}} Manuals & Examples"
        href: manuals/manuals.qmd
      - text: "{{< fa tv >}} Presentations & Videos"
        href: presentations/presentations.qmd
      - text: "{{< fa code >}} Code"
        href: api/api.qmd
    right:
      - icon: github
        href: https://github.com/Smolkaa

  sidebar:
    - title: "Home"
      border: true
      logo: /resources/logo/exess_logo.svg
      collapse-level: 1
      style: "floating"
      contents:
        - text: "Home"
          href: index.qmd
        - text: License
          href: LICENSE.md

    - title: "Documentation"
      contents:
        - documentation/documentation.qmd
        - documentation/acronyms.qmd
        - documentation/introduction/introduction.qmd
        - section: "2. Fundamentals"
          contents:
            - documentation/fundamentals/coordinate_systems.qmd
            - documentation/fundamentals/numerical_grids.qmd
            - "2.3 ODEs and Numerical Solvers"
            - documentation/fundamentals/stats_mc.qmd
            - documentation/fundamentals/exospheres.qmd
            - documentation/fundamentals/moon.qmd
            - "2.7 Other Exospheres in The Solar System"
        - section: "3. Planetary Measurements and Data"
          contents:
            - documentation/planetary_measurements/missions.qmd
            - documentation/planetary_measurements/lunar_exosphere_densities.qmd
        - section: "4. Exospheres: Sources and Sinks"
          contents:
            - "4.1 Solar Wind"
            - documentation/sources_sinks/thermal_sorption.qmd
            - documentation/sources_sinks/photoreactions.qmd
            - "Photodesorption"
            - "MIV"
        - section: "5. Exospheres: Particle Trajectories"
          contents:
            - documentation/trajectories/ballistic_trajectories.qmd
            - documentation/trajectories/non-ballistic_trajectories.qmd
        - section: "6. Lunar Water Exosphere Simulation"
          contents:
            - documentation/lunar_water_exosphere/conversion_model.qmd
        - section: "Appendix"
          contents:
            - documentation/referenced_value_library/referenced_value_library.qmd



    - title: "Manuals & Examples"
      contents:
        - text: " " 
          href: manuals/manuals.qmd


    - title: "Presentations & Videos"
      contents:
        - text: " " 
          href: presentations/presentations.qmd


    - title: "Code"
      contents:
        - text: "Home"
          href: api/api.qmd
        - section: "Base"
          contents:
            - api/base/constants.qmd
            - api/base/cs.qmd
            - api/base/distributions.qmd
            - api/base/utility.qmd
        - section: "Exospheres"
          contents:
            - api/exospheres/orbital_mechanics.qmd
            - api/exospheres/trajectory.qmd
        - section: "Numerical Grids"
          contents:
            - api/grids/global_structured_2d_grids.qmd
            - api/grids/global_structured_3d_grids.qmd
            - api/grids/utility.qmd
        - section: "Surfaces"
          contents:
            - api/surfaces/temperature.qmd

format:
  html:
    anchor-sections: true  
    code-copy: true
    code-link: true
    css: _styles.css
    filters:
      - lightbox
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 300px
    html-math-method: mathjax
    include-in-header: 
      - resources/mathjax.html
      - resources/head.html
    lightbox: auto
    link-external-newwindow: true
    mainfont: "'Roboto', sans-serif"
    monofont: "'Roboto Mono', monospace"
    theme: [flatly, _mystyle.scss]
    title-block-style: default
    toc: true
    toc-title: "{{< meta title >}}"

