---
title: "Student Thesis: On-Boarding Checklist"
image: play-solid.svg
author: Alexander Smolka
date: 28 07 23
categories:
  - On-Boarding
format:
  html:
    mermaid:
      theme: neutral
---
---

This page contains a checklist for students to get started working on their thesis based on the **ExESS** research project. While the [General Checklist](#sec-general) is applicable to students of all levels (Bachelor/Semester/Master) and all topics (theoretical/numerical/...); the other lists are only relevant for certains levels and topics. For questions, please contact me: [a.smolka@tum.de](mailto:a.smolka@tum.de).


## General Checklist {#sec-general}
This general checklist shall be completed in the first week(s) of your student thesis work.

- [ ] receive "LPE Thesis Starter Set"
  * read and understand the "Student Thesis Information" presentation slides
- [ ] open (and/or install) [RocketChat](https://chat.tum.de/home)
  * use RocketChat to send me a message containing one of the logical fallacies listed in the "Student Thesis Information"
- [ ] set up [LRZ Sync&Share](https://syncandshare.lrz.de/) online folder
- [ ] register your thesis
  * check the information on the registration document (LRZ Sync&Share folder), sign the document, and upload the signed registration to the same folder
- [ ] set up weekly meeting (including a fixed, weekly repeating outlook meeting)
  * please prepare a short presentation for each regular meeting, which should at a minimum contain two slides; one with a list of the tasks you have completed since the last meeting and one with a list of the tasks you plan to complete until the next meeting
- [ ] set up a time-plan for your thesis and include the plan in your first presentation (_see the example below_)


::: {.callout-note}
# Example Time-Plan

The first time-plan does not need to be (can not and should not be) very detailed. It should however give a rough overview of the tasks you plan to complete and the time you plan to spend on each task. The following is an example of a first draft of a time-plan for a 6-month thesis. The time-plan is written in [Mermaid](https://mermaid-js.github.io/mermaid/#/), which is a markdown-like language for generating diagrams. The Mermaid code is included in the source of this page, so you can copy it and modify it for your own time-plan. You can also use the [Mermaid Live Editor](https://mermaid-js.github.io/mermaid-live-editor/) to generate your own time-plan.

Over the course of your thesis, revisit the time-plan regularly and update it accordingly. This will help you to keep track of your progress and to identify potential problems early on. By adding more details to the time-plan over time, you will also have a good starting point for your thesis report.

```{mermaid}
gantt
  %% title Student Thesis Time-Plan
  dateFormat DD-MM
  axisFormat %m

  section On-Boarding
    On-Boarding Checklist: 01-01, 15d
    Learning Julia: 01-01, 01-03
  section Reading
    Reading Papers: 01-01, 01-04
  section Writing
    Continuous Documentation: 01-01, 15-05
    Thesis Writing: 15-04, 15-06
    Thesis Review: 15-06, 01-07
    Thesis Submission: milestone, 01-07
```
:::


## Numerical Based Thesis Checklist {#sec-numerical}
In case you are working on a numerical based thesis, the following checklist can help you get started with your work.

- [ ] set up [Julia](https://julialang.org/)
  * check out the list with recommended [Julia Resources]()
- [ ] set up the `ExESS` package (if applicable)
