---
title: "3.2.2 Maxwell-Boltzmann Flux Velocity Distribution"
---

{{< include /resources/latex/_defs.qmd >}}
{{< include /resources/latex/_symbols.qmd >}}

---

The [MBFD](/documentation/acronyms.qmd) (Maxwell-Boltzmann flux velocity distribution) is a modified three-dimensional [MBD](/documentation/drivers/thermal_sorption/maxwell_boltzmann_distribution.qmd), which is based on the upwards flux governed by the upwards velocity component. It is calculated by multiplying the Maxwell-Boltzmann velocity distribution by an additional velocity component and re-normalizing the [pdf](/documentation/acronyms.qmd) [@Brinkmann1970; @Armand1977; @Schoerghofer2022]. Let $n$ be a velocity-independent normalization factor, and $\velocity_z > 0$ the upwards velocity component, then the three-dimensional form of the [MBFD](/documentation/acronyms.qmd) can be written as
\begin{equation}
    f(\vec\velocity)d^3\vec\velocity = n \cdot \left(\frac{\mass}{2\pi\BoltzmannConstant\temperature}\right)^{3/2} \cdot \velocity_z \cdot \exp\left( -\frac{\mass\velocity^2}{2\BoltzmannConstant\temperature}\right) d^3\vec\velocity.
    \label{eq:mbfd_raw}
\end{equation}


To calculate the normalization factor $n$, the flux distribution can be integrated over spherical coordinates and set to unity, with the differential $d^3\vec\velocity = \velocity^2 \cos\sphericalCoordinateElevation\, d\velocity\, d\sphericalCoordinateAzimuth\, d\sphericalCoordinateElevation$ and domains $\velocity\in\Set{R}^+$, $\sphericalCoordinateElevation\in\left[-\pi/2, \pi/2\right)$, and $\sphericalCoordinateAzimuth\in\left[-\pi,\pi\right)$. After solving the three-dimensional integral, the normalization factor can be derived to
\begin{equation}
     n = 2\pi\sqrt{\frac{m}{2\pi\BoltzmannConstant\temperature}},
    \label{eq:mbfd_normalization_factor}
\end{equation}
which can be included in the original description of the [MBFD](/documentation/acronyms.qmd), given in Eq. \eqref{eq:mbfd_raw}, leading to
\begin{equation}
    f(\vec\velocity)d^3\vec\velocity = \frac{2}{\pi} \cdot \left(\frac{\mass}{2\BoltzmannConstant\temperature}\right)^2 \cdot \velocity_z \cdot \exp\left( -\frac{\mass\velocity^2}{2\BoltzmannConstant\temperature}\right) d^3\vec\velocity,
    \label{eq:mbfd}
\end{equation}
in cartesian coordinates with $d^3\vec\velocity = d\velocity_x \, d\velocity_y \, d\velocity_z$, or
\begin{equation}
    f(\vec\velocity)d^3\vec\velocity = \frac{2}{\pi} \cdot \left(\frac{\mass}{2\BoltzmannConstant\temperature}\right)^2 \cdot \velocity \sin\sphericalCoordinateElevation \cdot \exp\left( -\frac{\mass\velocity^2}{2\BoltzmannConstant\temperature}\right) d^3\vec\velocity,
    \label{eq:mbfd_spherical}
\end{equation}
in spherical coordinates with $d^3\vec\velocity = \velocity^2 \cos\sphericalCoordinateElevation \, d\velocity \, d\sphericalCoordinateElevation \, d\sphericalCoordinateAzimuth$ [@Brinkmann1970; @Armand1977; @Smith1978; @Schoerghofer2022].


{{< include boxes/_mbfd_components.qmd >}}


Through integration over the solid angles of Eq. \eqref{eq:mbfd_spherical}, the [MBFD](/documentation/acronyms.qmd) speed distribution emerges as
\begin{equation}
    f(\velocity)d\velocity =  2 \cdot \left(\frac{\mass}{2\BoltzmannConstant\temperature}\right)^2 \cdot \velocity^3 \cdot \exp\left( -\frac{\mass\velocity^2}{2\BoltzmannConstant\temperature}\right) d\velocity.
    \label{eq:mbfd_speed}
\end{equation}
Note that the scaling factor $2$ is a result of the integration over half the sphere through $\sphericalCoordinateElevation\in\left(0,\pi/2\right)$. As before, this speed distribution can be analyzed to extract typical speeds.


{{< include imgs/mbfd/_mbfd.qmd >}}


@fig-mbfd shows the probability densities of three [MBFD](/documentation/acronyms.qmd) distributed, normalized velocities. The normalization of the velocities has been performed with $\sqrt{\mass/\BoltzmannConstant\temperature} = 1$. The <tt>1D-MBFD</tt> curve shows the [pdf](/documentation/acronyms.qmd) of a velocity component perpendicular to the flux direction, which is equal to one-dimensional [MBD](/documentation/drivers/thermal_sorption/maxwell_boltzmann_distribution.qmd) velocities, which is equal to the scaled normal distribution $\mathcal{N}(0, \BoltzmannConstant\temperature/\mass)$. The second graph, <tt>1D-MBFD, flux</tt> shows the distribution of a directed velocity component in flux direction, $f_\parallel(\velocity)$, which is equal to
\begin{equation}
    f_\parallel (\velocity) d\velocity = 2\velocity \left(\frac{\mass}{2\BoltzmannConstant\temperature}\right) \cdot \exp\left(-\frac{\mass\velocity^2}{2\BoltzmannConstant\temperature}\right) d\velocity.
    \label{eq:mbfd_1d_parallel}
\end{equation}
Last, the graph <tt>3D-MBFD, speed</tt> shows the distribution of speeds of the three-dimensional form, given in Eq. \eqref{eq:mbfd_speed}. For the latter, the three typical speeds, the most probable speed $\velocity_p$, the mean speed $\meanof{\velocity}$ or the expected speed, and the root mean squared speed $\velocity_\text{rms}$, which are derived in the following section.

Note that, as with the speed, the angular components, the azimuth $\sphericalCoordinateAzimuth$ and elevation $\sphericalCoordinateElevation$, also have distinct probability distributions that can be analyzed. Similar to the Maxwell-Boltzmann velocity distribution, the azimuth angle is uniformly distributed which results in no favored direction of the horizontal velocity components. The vertical component is governed by the elevation angle, which is distributed according to its PDF
\begin{equation}
    f(\sphericalCoordinateElevation)d\sphericalCoordinateElevation = 2\sin\sphericalCoordinateElevation\cos\sphericalCoordinateElevation d\sphericalCoordinateElevation. \label{eq:mbfd_elevation}
\end{equation}
This leads to a mean elevation angle for the Maxwell-Boltzmann flux velocity distribution of
\begin{align}
        \meanof{\sphericalCoordinateElevation} &= \int_0^{\pi/2} 2\sphericalCoordinateElevation\sin\sphericalCoordinateElevation\cos\sphericalCoordinateElevation d\sphericalCoordinateElevation \nonumber \\
        &= \sphericalCoordinateElevation \sin^2\sphericalCoordinateElevation \Big|_0^{\pi/2} - \int_0^{\pi/2} \sin^2\sphericalCoordinateElevation d\sphericalCoordinateElevation = \frac{\pi}{2} - \frac{\pi}{4} = \frac{\pi}{4}.
\end{align}
@fig-mbfd_elevation shows the density plot of $\num{10^6}$ normalized samples of velocities of the [MBD](/documentation/drivers/thermal_sorption/maxwell_boltzmann_distribution.qmd) in a 2D plot with the vertical velocity $\velocity_3$ is plotted against the horizontal velocity $\sqrt{\velocity_1^2 + \velocity_2^2}$. For each sample, the angle between the x-axis and the velocity vector is the elevation angle, with the mean value $\meanof{\sphericalCoordinateElevation}$ included in the plot.



{{< include imgs/elevation/_mbfd_elevation.qmd >}}


### Typical Speeds

The most probable speed occurs at the maximum likelihood of the Eq. \eqref{eq:mbfd_speed}:
\begin{equation}
    \left. \frac{df(\velocity)}{d\velocity}\right|_{\velocity_p} = 0 \qquad \Rightarrow \qquad \velocity_p = \sqrt{\frac{3\BoltzmannConstant\temperature}{\mass}}.
    \label{eq:mbfd_most_probable_speed}
\end{equation}


The expected value of the speed distribution, the mean speed $\meanof{\velocity}$ is calculated by using the ensemble average equation:
\begin{equation}
    \meanof{\velocity} = \int_0^\infty \velocity f(\velocity) d\velocity = \sqrt{\frac{9\pi\BoltzmannConstant\temperature}{8\mass}} = \sqrt{\frac{3\pi}{8}} \,\cdot \velocity_p.
    \label{eq:mbfd_mean_speed}
\end{equation}

Lastly, the \gls{rms} speed is calculated as
\begin{equation}
    \velocity_\text{rms} = \sqrt{\meanof{\velocity^2}} = \left( \int_0^\infty \velocity^2 f(\velocity)d\velocity\right)^{1/2} = \sqrt{\frac{4\BoltzmannConstant\temperature}{\mass}} = \sqrt{\frac{4}{3}}\,\cdot \velocity_p.
    \label{eq:mbfd_rms_speed}
\end{equation}


{{< include boxes/_mbfd_typical_speeds.qmd >}}


{{< include tables/mbfd_typical_speeds/_mbfd_typical_speeds.qmd >}}


@tbl-mbfd_typical_speeds shows an overview of the speeds of the [MBFD](/documentation/acronyms.qmd) and their relation to the typical speeds. The $\velocity_{XX}$ denotes the speed at which the [cdf](/documentation/acronyms.qmd) evaluated to $F(\velocity_{XX}) = \int_0^{\velocity_{XX}} f(\velocity) d\velocity= XX\si{\percent}$. The entries are sorted by their [cdf](/documentation/acronyms.qmd) with the typical speeds highlighted and placed at the correct position. Note that $\velocity_{50}$ denotes the median of the distribution, which is not equal to the expected value $\meanof{\velocity}$. 


### Numerical Sampling

Let $\vec\Velocity$ be the random variable of the [MBFD](/documentation/acronyms.qmd) velocity, then any realization can be drawn from the respective [pdf](/documentation/acronyms.qmd):
\begin{equation}
    \vec\Velocity \sim f(\vec\velocity) = \frac{2}{\pi} \cdot \left(\frac{\mass}{2\BoltzmannConstant\temperature}\right)^2 \cdot \velocity_z \cdot \exp\left( -\frac{\mass\velocity^2}{2\BoltzmannConstant\temperature}\right)
\end{equation}
given in cartesian coordinates, see Eq. \eqref{eq:mbfd} and Eq. \eqref{eq:mbfd_spherical} for the function in spherical coordinates. Similar to the [MBD](/documentation/drivers/thermal_sorption/maxwell_boltzmann_distribution.qmd), the numerical sampling of the random variable can be performed by mapping each random component to one implemented numerical distribution. As a reminder, the most basic numerical distributions are the uniform distribution with random variable $\randomVariableUniform\in\left[0,1\right]$ with realization $\randomValueUniform$ of $\randomVariableUniform\sim f(\randomValueUniform)=1$ and a normal distribution with random variable $\randomVariableNormal\in\left(-\infty, \infty\right)$ with realization $\randomValueNormal$ of $\randomVariableNormal\sim f(\randomValueNormal) = \mathcal{N}\left(\randomValueNormal | 0, 1 \right)$ with zero mean and unit variance.


In cartesian coordinates, with $\vec\Velocity = \left(\Velocity_x, \Velocity_y, \Velocity_z\right)$, the first two directions are assumed to be perpendicular to the flux, while the z-direction is parallel to the flux. Thus, both the x- and the y-component, $\velocity_x$, and $\velocity_y$, can be numerically sampled like in the [MBD](/documentation/drivers/thermal_sorption/maxwell_boltzmann_distribution.qmd) with scaled normal distributions. The flux direction is drawn from the $f_\parallel$ [pdf](/documentation/acronyms.qmd), see Eq. \eqref{eq:mbfd_1d_parallel}, which can not be directly translated in either a uniform or a normal distribution. Therefore, the respective [cdf](/documentation/acronyms.qmd), $F_\parallel\left(\velocity_z\right)$,  must be matched with the uniform [cdf](/documentation/acronyms.qmd):
\begin{align}
    r_{\velocity_z} &= \int_0^{r_{\velocity_z}} f(\randomValueUniform) dr_u = \int_0^{\velocity_z} f_\parallel(\velocity) d\velocity = F_\parallel\left(\velocity_z\right) = 1 - \exp\left(-\frac{\mass\velocity_z^2}{2\BoltzmannConstant\temperature}\right) \\
    \Rightarrow\qquad \velocity_z &= \sqrt{-\ln\left(1-r_{\velocity_z}\right)\frac{2\BoltzmannConstant\temperature}{\mass}}.
    \label{eq:mbfd_random_cartesian_component}
\end{align}


$\vec\Velocity$ can also be expressed in spherical coordinates as $\vec\Velocity=\left(\Velocity_\velocity, \Velocity_\sphericalCoordinateElevation, \Velocity_\sphericalCoordinateAzimuth \right)$ with the differential $d^3\vec\velocity=\velocity^2 \, \cos\sphericalCoordinateElevation \, d\velocity d\sphericalCoordinateElevation d\sphericalCoordinateAzimuth$. The additional terms are distributed to the respective random variable:
\begin{alignat}{3}
    \Velocity_\velocity &\sim f(\velocity) && \qquad\text{with realization }\velocity, \\    
    \Velocity_\sphericalCoordinateElevation &\sim f(\sphericalCoordinateElevation) = 2\sin\sphericalCoordinateElevation\cos\sphericalCoordinateElevation && \qquad\text{with realization }\sphericalCoordinateElevation, \text{ and } \\    
    \Velocity_\sphericalCoordinateAzimuth &\sim f(\sphericalCoordinateAzimuth) = \frac{1}{2\pi} && \qquad\text{with realization }\sphericalCoordinateAzimuth.
\end{alignat}
As before, the [cdf](/documentation/acronyms.qmd) of the random variables can be set to equal the [cdf](/documentation/acronyms.qmd) of the unit uniform distribution:
\begin{alignat}{3}
    r_\velocity &= \int_0^{r_\velocity} f(\randomValueUniform) dr_u = \int_0^\velocity f(\tilde\velocity)d\tilde\velocity, \\
    r_\sphericalCoordinateElevation &= \int_0^{r_\sphericalCoordinateElevation} f(\randomValueUniform) dr_u = \int_0^\sphericalCoordinateElevation f(\tilde\sphericalCoordinateElevation)d\tilde\sphericalCoordinateElevation &&= 1 - \cos^2\sphericalCoordinateElevation, \label{eq:mbfd_random_elevation} \\
    r_\sphericalCoordinateAzimuth &= \int_0^{r_\sphericalCoordinateAzimuth} f(\randomValueUniform) dr_u = \int_{-\pi}^\sphericalCoordinateAzimuth f(\tilde\sphericalCoordinateAzimuth)d\tilde\sphericalCoordinateAzimuth &&= \frac{\sphericalCoordinateAzimuth+\pi}{2\pi}. \label{eq:mbfd_random_azimuth} 
\end{alignat}
While the latter two integrals are trivial, leading to a cosine-squared dependence of the elevation angle $\sphericalCoordinateElevation$ and a uniform dependence on the azimuth angle $\sphericalCoordinateAzimuth$, the speed integral evaluates to
\begin{equation}
    r_\velocity = 1 - \exp \left( -\frac{\mass\velocity^2}{2\BoltzmannConstant\temperature} \right) \cdot \left( \frac{\mass\velocity^2}{2\BoltzmannConstant\temperature} + 1\right).
    \label{eq:mbfd_random_speed}
\end{equation}
with no direct inversion of Eq. \eqref{eq:mbfd_random_speed}.


# ExESS API {.appendix .unnumbered}

- Type: [`MaxwellBoltzmannFluxVelocityDistribution`](/api/base/distributions.qmd). Creates a custom variable of type `MaxwellBoltzmannFluxVelocityDistribution` used to call the utility functions below.
- Function: [`velocity_cdf`](/api/base/distributions.qmd). Calculates the cumulative density of the velocity vector based on the given velocity distribution. See integrated Eqs. \eqref{eq:mbfd}, \eqref{eq:mbfd_spherical} 
- Function: [`velocity_pdf`](/api/base/distributions.qmd). Calculates the probability density of the velocity vector based on the given velocity distribution. See Eqs. \eqref{eq:mbfd}, \eqref{eq:mbfd_spherical}.
- Function: [`speed_cdf`](/api/base/distributions.qmd). Calculates the cumulative density of the speed based on the given velocity distribution. See integrated Eq. \eqref{eq:mbfd_speed}.
- Function: [`speed_pdf`](/api/base/distributions.qmd). Calculates the probability density of the speed based on the given velocity distribution. See Eq. \eqref{eq:mbfd_speed}. 
- Function: [`elevation_cdf`](/api/base/distributions.qmd). Calculates the cumulative density of the elevation angle based on the given velocity distribution. See integrated Eq. \eqref{eq:mbfd_elevation}.
- Function: [`elevation_pdf`](/api/base/distributions.qmd). Calculates the probability density of the elevation angle based on the given velocity distribution. See Eq. \eqref{eq:mbfd_elevation}.
- Function: [`speed`](/api/base/distributions.qmd). Computes the typical speeds of the given velocity distribution. See Eqs. \eqref{eq:mbfd_most_probable_speed}, \eqref{eq:mbfd_mean_speed}, \eqref{eq:mbfd_rms_speed}.
- Function: [`velocity`](/api/base/distributions.qmd). Draws a random, three-dimensional velocity vector based on the given velocity distribution. See Eq. \eqref{eq:mbfd_random_cartesian_component}.
- Function: [`speed`](/api/base/distributions.qmd). Draws a random speed based on the given velocity distribution. See Eq. \eqref{eq:mbfd_random_speed}.
- Function: [`elevation`](/api/base/distributions.qmd). Draws a random elevation angle based on the given velocity distribution. See Eq. \eqref{eq:mbfd_random_elevation}.
- Function: [`azimuth`](/api/base/distributions.qmd). Draws a random azimuth angle based on the given velocity distribution. See Eq. \eqref{eq:mbfd_random_azimuth}.



