::: {.column-body-outset-right}
::: {.callout-note}
# Cartesian and spherical components of the Maxwell-Boltzmann Flux velocity distribution.
Equations \eqref{eq:mbfd} and \eqref{eq:mbfd_spherical} can be devided into its three components of the respective coordinate system. Note that every component is representing a normalized [pdf](/documentation/acronyms.qmd) itself.

First, for cartesian coordinates $d^3\vec\velocity = d\velocity_x d\velocity_y d\velocity_z$:
\begin{alignat*}{6}
    f(\vec\velocity)d^3\vec\velocity &= \qquad\qquad\qquad f(\velocity_x) d\velocity_x &\cdot& \quad\qquad\qquad\qquad f(\velocity_y) d\velocity_y &\cdot& \quad\qquad\qquad\qquad f(\velocity_z) d\velocity_z \\
    &= \overbrace{\left(\frac{\mass}{2\pi\BoltzmannConstant\temperature}\right)^{1/2} \cdot \exp\left(-\frac{\mass\velocity_x^2}{2\BoltzmannConstant\temperature}\right) d\velocity_x} &\cdot& \; \overbrace{\left(\frac{\mass}{2\pi\BoltzmannConstant\temperature}\right)^{1/2} \cdot \exp\left(-\frac{\mass\velocity_y^2}{2\BoltzmannConstant\temperature}\right) d\velocity_y} &\cdot& \; \overbrace{2\pi\velocity_z \left(\frac{\mass}{2\pi\BoltzmannConstant\temperature}\right) \cdot \exp\left(-\frac{\mass\velocity_z^2}{2\BoltzmannConstant\temperature}\right) d\velocity_z},
\end{alignat*}
with
\begin{equation*}
    \int_{-\infty}^\infty f(\velocity_x) d\velocity_x = \int_{-\infty}^\infty f(\velocity_y) d\velocity_y = \int_0^\infty f(\velocity_z) d\velocity_z = 1.
\end{equation*}

Second, for spherical coordinates $d^3\vec\velocity = \velocity^2 \cos\sphericalCoordinateElevation \, d\velocity  d\sphericalCoordinateElevation  d\sphericalCoordinateAzimuth$:
\begin{alignat*}{6}
    f(\vec\velocity)d^3\vec\velocity &= \qquad\qquad\qquad f(\velocity) \, d\velocity &\cdot& \quad f(\sphericalCoordinateElevation) \, d\sphericalCoordinateElevation &\cdot& \;\quad f(\sphericalCoordinateAzimuth) \, d\sphericalCoordinateAzimuth \\
    &= \overbrace{2\cdot\left(\frac{\mass}{2\BoltzmannConstant\temperature}\right)^2 \cdot \velocity^3 \cdot \exp\left(-\frac{\mass\velocity^2}{2\BoltzmannConstant\temperature}\right) d\velocity} \; &\cdot& \quad \overbrace{2\sin\sphericalCoordinateElevation\cos\sphericalCoordinateElevation \; d\sphericalCoordinateElevation\phantom{\frac{1}{1}}} &\cdot& \quad \overbrace{\frac{1}{2\pi} \; d\sphericalCoordinateAzimuth},
\end{alignat*}
with
\begin{equation*}
    \int_0^\infty f(\velocity) d\velocity = \int_0^{\pi/2} f(\sphericalCoordinateElevation) \;d\sphericalCoordinateElevation = \int_{-\pi}^{\pi} f(\sphericalCoordinateAzimuth) \; d\sphericalCoordinateAzimuth = 1.
\end{equation*}
Note that all three-dimensional [pdf](/documentation/acronyms.qmd)s as well as their components are normalized.
:::
:::