[HEALPix](/documentation/acronyms.qmd), Hierarchical Equal Area iso-Latitude Pixelization [@Hardin2016], was developed by NASA to have three distinct properties, which are that

* the sphere is hierarchically tessellated into curvilinear quadrilaterals,
* the pixelization is an equal area partition of $\mathbb{S}^2$, and
* the point sets are distributed along fixed lines of latitude.


### Coordinate Calculation

The generation of such points firstly requires a division of the sphere into twelve equal area, four sided pixels defined by:
\begin{aligned}
    |\cos\sphericalCoordinateElevation|>\frac{2}{3}, \qquad \sphericalCoordinateAzimuth=m\frac{\pi}{2}, \qquad & \quad m = 0,1,2,3 \\
    \cos\sphericalCoordinateElevation = \frac{-2-4m}{3} + \frac{8\sphericalCoordinateAzimuth}{3\pi}, \qquad \frac{m\pi}{2} \leq \sphericalCoordinateAzimuth \leq \frac{(m+1)\pi}{2}, \qquad & \quad m=0,1,2,3 \\
    \cos\sphericalCoordinateElevation=\frac{2-4m}{3}-\frac{8\sphericalCoordinateAzimuth}{3\pi}, \qquad \frac{-(m+1)\pi}{2} \leq \sphericalCoordinateAzimuth \leq \frac{-m\pi}{2}, \qquad & \quad  m=0,1,2,3.
\end{aligned}

These pixels can be further partitioned into a $k \times k$ grid of sub-pixels of the same shape and area. The points of the set are located in the centers of each pixel. The subdivision leads to $k$ iso-latitudinal rings at the polar region $|\cos\sphericalCoordinateElevation|>2/3$, with
\begin{equation}
    |\cos\sphericalCoordinateElevation_i|=1-\frac{i^2}{3k^2}, \qquad \sphericalCoordinateAzimuth_j=\frac{\pi}{2i} \left( j - \frac{1}{2} \right),
\end{equation}

thus, every $i$-th ring has $4i$ equally spaced points. Closer to the equatorial region, $2k-1$ iso-latitudinal rings with $4k$ points each emerge. These points are indexed by $k \leq |i| \leq 2k$ and $1 \leq j \leq 4k$:
\begin{equation}
    |\cos\sphericalCoordinateElevation_i| = \frac{4}{3} - \frac{2i}{3k}, \qquad \sphericalCoordinateAzimuth_j = \frac{\pi}{2k} \left( j - \frac{s}{2} \right), \qquad s = (i-k+1) \mod 2.
\end{equation}

The last index, $s$, describes the phase shift between the rings. Finally, this configuration produces a set of $N=12k^2$ points [@Hardin2016].


### Area Calculation


### Continuous to Discrete Mapping