## LACE
The [LACE](/documentation/acronyms.qmd) (Lunar Atmospheric Composition Experiment) on the Apollo 17 mission was part of the [ALSEP](/documentation/acronyms.qmd) (Apollo Lunar Surface Experiments Package) to investigate the composition and variation of the Moon's exosphere. Specifically designed for the mission, the instrument consisted of a small, remotely operated package containing a mass spectrometer coupled with a pressure sensor. With its opening oriented upward, it was able to measure the downward stream of particles at the lunar surface at the Apollo 17 landing location, the Taurus-Littrow Valley. On December 27, 1971, the instrument was activated to start the data acquisition process $\SI{50}{\hour}$ after local sunset to operate through one entire lunar night. Increasing exospheric number densities at the morning-terminator as well as higher outgassing rates led to elevated background gas levels and prompted the temporary suspension of operations during the lunar day, except a short check near $\SI{12}{\hour}$ local time. In total, the [LACE](/documentation/acronyms.qmd) measured the nighttime densities for nine lunations. [@Hoffman1975; @Killen2019]


The instrument's mass spectrometer measured the mass per unit charge ratio up to a maximum of $\SI{110}{}$ in three mass ranges $\SI{1}{}$ to $\SI{4}{}$, $\SI{12}{}$ to $\SI{48}{}$, and $\SI{27.4}{}$ to $\SI{110}{}$ termed low, medium, and high. A triple-channel analyzer was able to capture data from all three ranges simultaneously as counts per $\SI{0.6}{\second}$ at every voltage step [@Hoffman1975]. Note that due to the measurement technique ambiguous data points of particles with double mass being doubly ionized were taken [@Killen2019].

## LADEE

The [LADEE](/documentation/acronyms.qmd) (Lunar Atmosphere and Dust Environment Explorer) mission was created in 2008 to address the goals identified in the decadal survey report "Scientific Context for Exploration of the Moon", which highlighted the lunar atmosphere as a priority for future lunar science missions. Among its main mission objectives was to determine the composition of the lunar exosphere, as well as its distribution and variability. On April 18^th^, 2014, [LADEE](/documentation/acronyms.qmd) was decommissioned through impact into the Moon after around $\SI{100}{\day}$ of nominal science operations. The gathered data was processed and submitted to the [NASA](/documentation/acronyms.qmd) [PDS](/documentation/acronyms.qmd) (Planetary Data System) for public access [@LADEE2014]. The [NMS](/documentation/acronyms.qmd) (Neutral Mass Spectrometer) aboard the spacecraft measured the mass distribution of neutral species over a mass-to-charge range between $\SI{2}{}$ to $\SI{150}{}$. With its retrograde, equatorial orbit around the Moon, [LADEE](/documentation/acronyms.qmd) conducted systematic surveys of helium, neon, and argon densities confined in a $\pm\SI{23}{\degree}$ near-equatorial band with altitudes ranging between $\SI{4}{}$ and $\SI{61}{\kilo\metre}$ [@Benna2015].
[{{< fa link >}} [pds-atmospheres.nmsu.edu](https://pds-atmospheres.nmsu.edu/ data_and_services/atmospheres_data/LADEE/mainr.html) </br> last visited: May 2023]{.aside}


{{< include /documentation/planetary_measurements/lunar_exosphere_densities/imgs/ladee_n0/_ladee_n0.qmd >}}