---
title: "2.1.1 Coordinates"

---

{{< include /resources/latex/_defs.qmd >}}
{{< include /resources/latex/_symbols.qmd >}}

---


A clear distinction has been made between cartesian and spherical coordinates and cartesian and spherical elements. The former is used to describe the domain in which the vector is defined, while the latter is used to describe the vector and its components themselves. For example, a position vector in a cartesian coordinate system, $\cartesianCoordinate$, can be expressed in cartesian elements $\left(\cartesianCoordinateX, \cartesianCoordinateY, \cartesianCoordinateZ\right)$, which are the x-, y-, and z-components of the vector:
\begin{equation}
    \cartesianCoordinate = \begin{bmatrix}
        \cartesianCoordinateX \\ 
        \cartesianCoordinateY \\ 
        \cartesianCoordinateZ 
    \end{bmatrix} \qquad\text{with } \cartesianCoordinateX\in\Set{R},\;\cartesianCoordinateY\in\Set{R},\;\cartesianCoordinateZ\in\Set{R}.
    \label{eq:cartesian_coordinate}
\end{equation}


The same vector in the same coordinate system and, thus, the same domain can also be expressed using spherical elements $\left(\sphericalCoordinateRadius, \sphericalCoordinateAzimuth, \sphericalCoordinateElevation\right)$, which are the radial, azimuthal, and elevation components of the vector:
\begin{equation}
    \cartesianCoordinate_s = \begin{bmatrix}
        \sphericalCoordinateRadius \cos\sphericalCoordinateAzimuth \cos\sphericalCoordinateElevation \\ 
        \sphericalCoordinateRadius \sin\sphericalCoordinateAzimuth \cos\sphericalCoordinateElevation \\ 
        \sphericalCoordinateRadius \sin\sphericalCoordinateElevation 
    \end{bmatrix} \qquad\text{with }\sphericalCoordinateRadius\in\Set{R}^+,\;\sphericalCoordinateAzimuth\in\left[-\pi,\pi\right),\;\sphericalCoordinateElevation\in\left[-\frac{\pi}{2},\frac{\pi}{2}\right].
    \label{eq:cartesian_coordinate_spherical_elements}
\end{equation}
Note that the subscript $s$ indicates that the vector is expressed in spherical elements. Both vectors describe the same coordinate in the same coordinate system, thus $\cartesianCoordinate = \cartesianCoordinate_s$. On the other hand, a coordinate can also be projected into a spherical coordinate system, $\sphericalCoordinate$, which is a different domain, and expressed in spherical elements $\left(\sphericalCoordinateRadius, \sphericalCoordinateAzimuth, \sphericalCoordinateElevation\right)$:
\begin{equation}
    \sphericalCoordinate = \begin{bmatrix}\sphericalCoordinateRadius \\ \sphericalCoordinateAzimuth \\ \sphericalCoordinateElevation \end{bmatrix} \qquad\text{with }\sphericalCoordinateRadius\in\Set{R}^+,\;\sphericalCoordinateAzimuth\in\left[-\pi,\pi\right),\;\sphericalCoordinateElevation\in\left[-\frac{\pi}{2},\frac{\pi}{2}\right].
    \label{eq:spherical_coordinate}
\end{equation}


The same coordinate can also be expressed in cartesian elements $\left(\cartesianCoordinateX, \cartesianCoordinateY, \cartesianCoordinateZ\right)$:
\begin{equation}
    \sphericalCoordinate_c = \begin{bmatrix}
        \sqrt{\cartesianCoordinateX^2 + \cartesianCoordinateY^2 + \cartesianCoordinateZ^2} \\ 
        \sgn\left(\cartesianCoordinateY\right)\cdot\cos^{-1}\left(\frac{\cartesianCoordinateX}{\sqrt{\cartesianCoordinateX^2 + \cartesianCoordinateY^2}}\right)\\
        \sin^{-1}\left(\frac{\cartesianCoordinateZ}{\sqrt{\cartesianCoordinateX^2 + \cartesianCoordinateY^2 + \cartesianCoordinateZ^2}}\right) 
    \end{bmatrix}  \qquad\text{with } \cartesianCoordinateX\in\Set{R},\;\cartesianCoordinateY\in\Set{R},\;\cartesianCoordinateZ\in\Set{R}.
    \label{eq:spherical_coordinate_cartesian_elements}
\end{equation}


Note that the subscript $c$ indicates that the vector is expressed in cartesian elements. Both vectors describe the same coordinate in the same coordinate system, thus $\sphericalCoordinate = \sphericalCoordinate_c$. Even though physically speaking, all four coordinate vectors can describe the same position in physical space, mathematically speaking, they are different vectors, thus: $\cartesianCoordinate = \cartesianCoordinate_s \neq \sphericalCoordinate = \sphericalCoordinate_c$. The following sections will go into more detail about the differences between these coordinate systems, where the names \emph{cartesian} and \emph{spherical} are used to describe the domain and not the elements.


All coordinate vectors can also be written as a sum of scaled base vectors, where the base vectors are the unit vectors of the respective coordinate system. The base vectors of any cartesian coordinate system are:
\begin{equation}
    \cartesianBaseVectorX = \begin{bmatrix}1 \\ 0 \\ 0 \end{bmatrix} \text{,}\qquad
    \cartesianBaseVectorY = \begin{bmatrix}0 \\ 1 \\ 0 \end{bmatrix} \text{,}\qquad\text{and}\qquad
    \cartesianBaseVectorZ = \begin{bmatrix}0 \\ 0 \\ 1 \end{bmatrix},
\end{equation}
which leads to the following expression for the cartesian coordinate vector for both cartesian and spherical elements:
\begin{align}
    \cartesianCoordinate &= \cartesianCoordinateX \cartesianBaseVectorX + \cartesianCoordinateY \cartesianBaseVectorY + \cartesianCoordinateZ \cartesianBaseVectorZ \nonumber \\
    &= \left(\sphericalCoordinateRadius \cos\sphericalCoordinateAzimuth \cos\sphericalCoordinateElevation\right)\cartesianBaseVectorX + \left(\sphericalCoordinateRadius \sin\sphericalCoordinateAzimuth \cos\sphericalCoordinateElevation\right) \cartesianBaseVectorY + \left(\sphericalCoordinateRadius \sin\sphericalCoordinateElevation\right) \cartesianBaseVectorZ = \cartesianCoordinate_s.
\end{align}
Similarly, the base vectors of any spherical coordinate system are:
\begin{equation}
    \sphericalBaseVectorRadius = \begin{bmatrix}1 \\ 0 \\ 0 \end{bmatrix} \text{,}\qquad
    \sphericalBaseVectorAzimuth = \begin{bmatrix}0 \\ 1 \\ 0 \end{bmatrix} \text{,}\qquad\text{and}\qquad
    \sphericalBaseVectorElevation = \begin{bmatrix}0 \\ 0 \\ 1 \end{bmatrix},
\end{equation}
which leads to the following expression for the spherical coordinate vector for both cartesian and spherical elements:
\begin{align}
    \sphericalCoordinate &= \sphericalCoordinateRadius \sphericalBaseVectorRadius + \sphericalCoordinateAzimuth \sphericalBaseVectorAzimuth + \sphericalCoordinateElevation \sphericalBaseVectorElevation \nonumber \\
    &= \left(\sqrt{\cartesianCoordinateX^2 + \cartesianCoordinateY^2 + \cartesianCoordinateZ^2}\right)\sphericalBaseVectorRadius \nonumber \\
    &+ \left(\sgn\left(\cartesianCoordinateY\right)\cdot\cos^{-1}\left(\frac{\cartesianCoordinateX}{\sqrt{\cartesianCoordinateX^2 + \cartesianCoordinateY^2}}\right)\right) \sphericalBaseVectorAzimuth \nonumber \\
    &+ \left(\sin^{-1}\left(\frac{\cartesianCoordinateZ}{\sqrt{\cartesianCoordinateX^2 + \cartesianCoordinateY^2 + \cartesianCoordinateZ^2}}\right)\right) \sphericalBaseVectorElevation \\
    &= \sphericalCoordinate_c.\nonumber
\end{align}

Due to the equalities of the vectors in their respective coordinate system, the rest of this work will only use $\cartesianCoordinate$ and $\sphericalCoordinate$ without their indexed counterparts. The element type will be indicated by the context of the equation. 


# ExESS API {.appendix .unnumbered}

- Types: [`GlobalCartesianPosition`](/api/base/cs.qmd) & [`GlobalCartesianVelocity`](/api/base/cs.qmd). Custom types that define custom position and velocity vectors in a three-dimensional **cartesian** coordinate system with **cartesian** elements. See Eq. \eqref{eq:cartesian_coordinate}.
- Types: [`GlobalSphericalPosition`](/api/base/cs.qmd) & [`GlobalSphericalVelocity`](/api/base/cs.qmd). Custom types that define custom position and velocity vectors in a three-dimensional **spherical** coordinate system with **spherical** elements. See Eq. \eqref{eq:spherical_coordinate}.
