---
title: "Two-Dimensional Landing Position Calculation"
format:
  html: default
---

{{< include /resources/latex/_defs.qmd >}}
{{< include /resources/latex/_symbols.qmd >}}

::: {.hidden }
# {{< meta title >}} {.unnumbered}
:::

---

The following calculations are based on the orbital mechanics functions introduced in section [Orbital Mechanics Functions](/documentation/trajectories/orbital_mechanics_functions.qmd) to calculate the landing position $\left(\longitude_1, \latitude_1\right)$. Note that this approach is quasi-two-dimensional as the radial dimension of the spherical three-dimensional coordinate system is neglected, assuming a perfectly spherical central body. The trajectory starts and the launch position $\left(\longitude_0, \latitude_0\right)$ and, as mentioned above, requires knowledge about the mass and radius of the planetary body, $\mass$ and $\radius$, as well as the launch, or initial, velocity vector $\vec\velocity$.


Based on the escape velocity [$\velocity_{esc}(\radius, \mass)$](/documentation/trajectories/orbital_mechanics_functions.qmd#sec-escape-velocity), the relative kinetic energy fraction [$\relativeKineticEnergy(\vec\velocity, \velocity_{esc})$](/documentation/trajectories/orbital_mechanics_functions.qmd#sec-relative-kinetic-energy), can be determined, which in turn is used to calculate the semi-major axis of the trajectory, [$\semiMajorAxis(\radius, \relativeKineticEnergy)$](/documentation/trajectories/orbital_mechanics_functions.qmd#sec-semi-major-axis). Since the launch velocity vector is given in local cartesian coordinates, both its zenith angle [$\zenithAngle(\vec\velocity)$](/documentation/trajectories/orbital_mechanics_functions.qmd#sec-zenith-angle) and its azimuth angle [$\azimuthAngle\left(\vec\velocity\right)$](/documentation/trajectories/orbital_mechanics_functions.qmd#sec-azimuth-angle) can be directly extracted. The former is subsequently used for the determination of the eccentricity [$\eccentricity\left(\relativeKineticEnergy, \zenithAngle\right)$](/documentation/trajectories/orbital_mechanics_functions.qmd#sec-eccentricity). With both $\semiMajorAxis$ and $\eccentricity$ known, the true anomaly at launch $\trueAnomaly_0(\radius, \semiMajorAxis, \eccentricity)$, and due to symmetry conditions, also the landing position [$\trueAnomaly_1 = 2\pi - \trueAnomaly_0$](/documentation/trajectories/orbital_mechanics_functions.qmd#sec-true-anomaly), can be calculated. The angular difference between the landing and launch true anomaly $\trueAnomaly_1 - \trueAnomaly_0 = 2\pi - 2\trueAnomaly = \Delta\trueAnomaly$ can then easily be converted into the ground track distance of the projected trajectory [$d(\radius, \Delta\trueAnomaly)$](/documentation/trajectories/orbital_mechanics_functions.qmd#sec-ground-track-distance).


Based on @Schoerghofer2022a, the landing position $\left(\longitude_1, \latitude_1\right)$ can now be calculated using the launch position $\left(\longitude_0, \latitude_0\right)$, the ground track distance $d$, and the azimuth angle $\azimuthAngle$ as
\begin{align}
    \sin\latitude_1 &= \sin\left(\frac{d}{\radius}\right) \cdot \cos\latitude_0 \cdot \cos\azimuthAngle + \cos\left(\frac{d}{\radius}\right) \cdot \sin\latitude_0 \\
    \cos\Delta\longitude &= \cos\left(\frac{d}{\radius}\right) \cdot \cos\latitude_0 - \sin\left(\frac{d}{\radius}\right) \cdot \sin\latitude_0 \cdot \cos\azimuthAngle \cdot \cos^{-1}\latitude_1 \\
    \Rightarrow \longitude_1 &= \longitude_0 + \sgn\left(\velocity_1\right)\cdot\Delta\longitude,
\end{align}
with the signum function $\sgn\left(\velocity_1\right) = 1$ for $\velocity_1\geq0$ and $\sgn\left(\velocity_1\right) = -1$ for $\velocity_1<0$.


Calculating the time of flight $\flightTime = \Time_1 - \Time_0 = \period - 2\Time_0$ requires the orbital period [$\period\left(\semiMajorAxis, \mass\right)$](/documentation/trajectories/orbital_mechanics_functions.qmd#sec-orbit-period) as well as the orbit time [$\Time(\meanAnomaly, \period)$](/documentation/trajectories/orbital_mechanics_functions.qmd#sec-orbit-time), where $\Time_0$ and $\Time_1$ are the orbit times at the launch and landing, respectively, with $\Time_1 = \period-\Time_0$ for symmetry reasons. The mean anomaly [$\meanAnomaly_0$](/documentation/trajectories/orbital_mechanics_functions.qmd#sec-mean-anomaly) at launch can be calculated using the eccentric anomaly [$\eccentricAnomaly_0$](/documentation/trajectories/orbital_mechanics_functions.qmd#sec-eccentric-anomaly) and the eccentricity $\eccentricity$.
