---
title: "Lunar Exosphere Surface Densities"
tbl-colwidths: [45,23,32]
---

{{< include /resources/latex/_defs.qmd >}}
{{< include /resources/latex/_symbols.qmd >}}

::: {.hidden }
# {{< meta title >}} {.unnumbered}
:::

---

This section lists referenced values of the lunar exosphere surface densities, generally provided as a number density in $\left[\si{\centi\metre\tothe{-3}}\right]$. Some references are providing their values in terms of a column density in $\left[\si{\centi\metre\tothe{-2}}\right]$, which includes the respectives measurements coulumn height, i.e., the illuminated line of sight of brightness measurements like LAMP.

See the additional information section on this section's appendix to find details about some sources, their assumptions, and their measurement methods.

# Atomic Hydrogen -- $\ce{H}$
{{< include lunar_exosphere_densities/_H.qmd >}}

# Molecular Hydrogen -- $\ce{H2}$
{{< include lunar_exosphere_densities/_H2.qmd >}}

# Helium -- $\ce{He}$
{{< include lunar_exosphere_densities/_He.qmd >}}

# Hydroxyl -- $\ce{OH}$
{{< include lunar_exosphere_densities/_OH.qmd >}}

# Water -- $\ce{H2O}$
{{< include lunar_exosphere_densities/_H2O.qmd >}}

# Neon -- $\ce{Ne}$
{{< include lunar_exosphere_densities/_Ne.qmd >}}

# Argon -- $\ce{Ar}$


# Additional Information {.appendix .unnumbered}

* @Gladstone2009 assume for the LAMP derivations a  $\SI{30}{\minute}$, $3\sigma$ observation, and a path length of $\SI{300}{\kilo\metre}$.
* @Hodges1973 assumed a solar wind proton influx of $3 \times 10^8 \si{\second\tothe{-1}\centi\metre\tothe{-3}}$ for their simulations.
* CHACE measurements were made during a Moon's pass through Earth's magnetotail, reducing the solar wind influx of particles dramatically.
* @Heiken1991 reported a joint upper limit of $0.5 \times 10^0$ for both $\ce{OH}$ and $\ce{H2O}$