---
title: "3.1 Solar Wind"
---

{{< include /resources/latex/_defs.qmd >}}
{{< include /resources/latex/_symbols.qmd >}}

---

# Origin

Parker Spirals of the Sun because of the solar rotation [@Bittencourt2004].

The rotation axis of the Sun is inclined by $\SI{7.25}{\degree}$ with respect to the ecliptic plane [@Russell2013].


$\SI{400}{\kilo\metre\per\second}$ [@Russell2013]

$\left(\num{400} - \num{500}\right)\si{\kilo\metre\per\second}$ nominal speed [@Bennett2013; @Farrell2015]

Drift velocity of electrons: $\SI{300}{\kilo\metre\per\second}$ [@Bittencourt2004]

Mariner 2 measurements of the velocity at the near-Earth rotation: $\left(\num{400} - \num{700}\right)\si{\kilo\metre\per\second}$ based on a roughly $\SI{27}{\day}$ cycle [@Neugebauer1966].

# Composition

The solar wind is a magnetized and highly conducting plasma consisting of electrons, protons, and heavier ions. At Earth's distance to the Sun, its nominal density is about $\SI{5}{\centi\metre\tothe{-3}}$ electrons and ions [@Russell2013]. For the Moon, this density can vary greatly based on transient events like [CME](/documentation/acronyms.qmd){.abbr title="Coronal Mass Ejection"} or the Moon's passage through Earth's magnetotail.

With the solar wind propagating in all directions, the density decreases inversely proportional to the square of the distance from the Sun. 

## Protons and Electrons

About $\SI{96}{\percent}$ of all ions are protons [@Futaana2012].

Proton density of the solar wind measured by Mariner 2 varied between $\left(\num{1} - \num{50}\right)\si{\centi\metre\tothe{-3}}$, with an average daily average of $\SI{5}{\centi\metre\tothe{-3}}$ protons [@Neugebauer1966].

## Ions and Heavier Elements

The majority of the remaining ions are alpha particles, i.e., helium nuclei $\ce{He++}$, making up about $\SI{4}{\percent}$ of the solar wind ion particles [@Futaana2012].

# Interplanetary Magnetic Field

The solar wind exerts a magnetic field, called the Interplanetary Magnetic Field ([IMF](/documentation/acronyms.qmd){.abbr title="Interplanetary Magnetic Field"}), of roughly $\SI{5}{\nano\tesla}$ in the ecliptic plane at $\SI{1}{AU}$, though its orientation is highly variable [@Russell2013]. @Zhao1995 reported that in situ observations round that the horizontal component of the IMF, while being generally less than $\SI{5}{\nano\tesla}$ in strength, "jumps from one finite value to another with opposite polarity".


{{< include solar_wind/imgs/imf_bx_jumping/_imf_bx_jumping.qmd >}}


Due to its high conductivity, the solar wind's magnetic field tends to be relatively frozen inside the streaming plasma [@Bittencourt2004].


# Interaction with the Lunar Surface

## Distribution

Assuming that the particles in the solar wind are spatially evenly distributed, the particle distribution on the planetary surface is only a function of the solar zenith angle $\zenith_s$. This angle can be derived in terms of the sub-solar longitude $\longitude_s$ and latitude $\latitude_s$ by $\cos\zenith_s = \cos\longitude_s \cdot \cos\latitude_s$.

Let $\left(\longitude_s, \latitude_s\right)$ be a spherical sub-solar surface coordinate with $\sphericalCoordinateRadius$ equal to the central body's radius. For positive solar zenith angles, the PDF of the solar wind particle distribution on the surface is 
\begin{equation}
    f(\longitude_s, \latitude_s) d\longitude d\latitude = \frac{1}{4} \cos\zenith_s d\longitude d\latitude = \frac{1}{4} \cos\longitude_s \cos\latitude_s d\longitude d\latitude, \label{eq:solar_wind_position_pdf}
\end{equation}
which can be integrated over the angular arguments of the dayside hemisphere, which is $-\pi / 2 \leq \longitude_s \leq \pi / 2$ and $-\pi / 2 \leq \latitude_s \leq \pi / 2$, to yield the CDF
\begin{equation}
    F(\longitude_s, \latitude_s) = \int_{-\pi/2}^{\latitude_s} \int_{-\pi/2}^{\longitude_s} \frac{1}{4} \cos\longitude \cos\latitude d\longitude d\latitude = \frac{1}{4} \left(1 - \sin\longitude_s\right) \left(1 - \sin\latitude_s\right). \label{eq:solar_wind_position_cdf}
\end{equation}
The two arguments can easily be separated into two individual CDFs, one for each angular position:
\begin{align}
    F(\longitude_s) &= \frac{1}{2} \left(1 - \sin\longitude_s\right) \\
    F(\latitude_s) &= \frac{1}{2} \left(1 - \sin\latitude_s\right).
\end{align}

For the numerical sampling of this distribution, let $\randomVariableUniform \in \left[0, 1\right]$ be a uniformly distributed random variable with realization $\randomValueUniform$ of $\randomVariableUniform \sim f(\randomValueUniform) = 1$. The CDFs can be set equal to such realization and through the inversion technique, a numerical function for the sampling of the surface coordinates can be found. 
\begin{align}
    \randomValueUniform &= F(\longitude_s) = \frac{1}{2} \left(1 - \sin\longitude_s\right) \quad\Rightarrow\quad \longitude_s = \sin^{-1}\left(1 - 2 \randomValueUniform\right) \\
    \randomValueUniform &= F(\latitude_s) = \frac{1}{2} \left(1 - \sin\latitude_s\right) \quad\Rightarrow\quad \latitude_s = \sin^{-1}\left(1 - 2 \randomValueUniform\right).
\end{align}

{{< include solar_wind/imgs/surface_distribution/_surface_distribution.qmd >}}




[ ]{.aside}