---
title: "Orbital Mechanics"
---

::: {.hidden }
# {{< meta title >}}
:::

---

## Usage

## API

::: {.callout-note appearance="simple" icon=false}
# ``azimuth_angle_v`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.azimuth_angle_v
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``eccentric_anomaly_e_M`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.eccentric_anomaly_e_M
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``eccentric_anomaly_e_theta`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.eccentric_anomaly_e_theta
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``eccentricity_epskin_psi`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.eccentricity_epskin_psi
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``eccentricity_epskin_v`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.eccentricity_epskin_v
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``eccentricity_r_m_v`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.eccentricity_r_m_v
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``escape_velocity_r_m`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.escape_velocity_r_m
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``flight_time_t0_t1`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.flight_time_t0_t1
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``flight_time_t0_P`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.flight_time_t0_P
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``flight_time_e_theta0_theta1_P`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.flight_time_e_theta0_theta1_P
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``flight_time_e_theta0_P`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.flight_time_e_theta0_P
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``epskin_vesc_v`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.epskin_vesc_v
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``epskin_r_m_v`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.epskin_r_m_v
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``epskin_r_a`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.epskin_r_a
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``epskin_e_theta`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.epskin_e_theta
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``ground_distance_R_dtheta`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.ground_distance_R_dtheta
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``ground_distance_R_a_e`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.ground_distance_R_a_e
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``mean_anomaly_e_E`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.mean_anomaly_e_E
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``mean_anomaly_e_theta`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.mean_anomaly_e_theta
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``orbit_period_a_m`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.orbit_period_a_m
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``orbit_time_M_P`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.orbit_time_M_P
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``orbit_time_e_E_P`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.orbit_time_e_E_P
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``orbit_time_e_theta_P`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.orbit_time_e_theta_P
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``semi_latus_rectum_a_e`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.semi_latus_rectum_a_e
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``semi_latus_rectum_r_e_theta`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.semi_latus_rectum_r_e_theta
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``semi_major_axis_r_epskin`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.semi_major_axis_r_epskin
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``semi_major_axis_r_m_v`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.semi_major_axis_r_m_v
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``semi_major_axis_p_e`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.semi_major_axis_p_e
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``semi_major_axis_r_e_theta`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.semi_major_axis_r_e_theta
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``true_anomaly_r_a_e`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.true_anomaly_r_a_e
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``true_anomaly_e_epskin`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.true_anomaly_e_epskin
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``true_anomaly_epskin_v`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.true_anomaly_epskin_v
```
:::

::: {.callout-note appearance="simple" icon=false}
# ``zenith_angle_v`` -- Function
```{julia}
#| echo: false
if !isdefined(Main, :ExESS)
include(joinpath(@__DIR__, "..", "..", "..", "exess.jl", "src", "ExESS.jl"))
using .ExESS
end
@doc ExESS.zenith_angle_v
```
:::