The [LADEE](/documentation/acronyms.qmd) (Lunar Atmosphere and Dust Environment Explorer) mission was created in 2008 to address the goals identified in the decadal survey report "Scientific Context for Exploration of the Moon", which highlighted the lunar atmosphere as a priority for future lunar science missions. Among its main mission objectives was to determine the composition of the lunar exosphere, as well as its distribution and variability. On April 18^th^, 2014, [LADEE](/documentation/acronyms.qmd) was decomissioned through impact into the Moon after around $\SI{100}{\day}$ of nominal science operations. The gathered data was processed and submitted to the [NASA](/documentation/acronyms.qmd) [PDS](/documentation/acronyms.qmd) (Planetary Data System) for public access [@LADEE2014]. The [NMS](/documentation/acronyms.qmd) (Neutral Mass Spectrometer) aboard the spacecraft measured the mass distribution of neutral species over a mass-to-charge range between $\SI{2}{}$ to $\SI{150}{}$. With its retrograde, equatorial orbit around the Moon, [LADEE](/documentation/acronyms.qmd) conducted sytematic surveys of helium, neon, and argon densities confined in a $\pm\SI{23}{\degree}$ near-equatorial band with altitudes ranging between $\SI{4}{}$ and $\SI{61}{\kilo\metre}$ [@Benna2015].
[{{< fa link >}} [pds-atmospheres.nmsu.edu](https://pds-atmospheres.nmsu.edu/ data_and_services/atmospheres_data/LADEE/mainr.html) </br> last visited: May 2023]{.aside}

## Projected Surface Number Densities

{{< include /documentation/planetary_measurements/missions/img/ladee_n0/_ladee_n0.qmd >}}