The [MBFD](/documentation/acronyms.qmd) (Maxwell-Boltzmann flux velocity distribution) is a modified three-dimensional [MBD](/documentation/acronyms.qmd), which is based on the upwards flux governed by the upwards velocity component. It is calculated by multiplying Eq. \eqref{eq:mbd_3d} by this additional velocity component and re-normalizing the [pdf](/documentation/acronyms.qmd) [@Brinkmann1970; @Armand1977; @Schoerghofer2022]. Let $n$ be a velocity-independent normalization factor, and $\velocity_z > 0$ the upwards velocity component, then the three-dimensional form of the [MBFD](/documentation/acronyms.qmd) can be written as
\begin{equation}
    f(\vec\velocity)d^3\vec\velocity = n \cdot \left(\frac{\mass}{2\pi\BoltzmannConstant\temperature}\right)^{3/2} \cdot \velocity_z \cdot \exp\left( -\frac{\mass\velocity^2}{2\BoltzmannConstant\temperature}\right) d^3\vec\velocity.
    \label{eq:mbfd_raw}
\end{equation}


To calculate the normalization factor $n$, the flux distribution can be integrated over spherical coordinates and set to unity, with the differential $d^3\vec\velocity = \velocity^2 \cos\sphericalCoordinateElevation\, d\velocity\, d\sphericalCoordinateAzimuth\, d\sphericalCoordinateElevation$ and domains $\velocity\in\Set{R}^+$, $\sphericalCoordinateElevation\in\left[-\pi/2, \pi/2\right)$, and $\sphericalCoordinateAzimuth\in\left[-\pi,\pi\right)$. After solving the three-dimensional integral, the normalization factor can be derived to
\begin{equation}
     n = 2\pi\sqrt{\frac{m}{2\pi\BoltzmannConstant\temperature}},
    \label{eq:mbfd_normalization_factor}
\end{equation}
which can be included in the original description of the [MBFD](/documentation/acronyms.qmd), given in Eq. \eqref{eq:mbfd_raw}, leading to
\begin{equation}
    f(\vec\velocity)d^3\vec\velocity = \frac{2}{\pi} \cdot \left(\frac{\mass}{2\BoltzmannConstant\temperature}\right)^2 \cdot \velocity_z \cdot \exp\left( -\frac{\mass\velocity^2}{2\BoltzmannConstant\temperature}\right) d^3\vec\velocity,
    \label{eq:mbfd}
\end{equation}
in cartesian coordinates with $d^3\vec\velocity = d\velocity_x \, d\velocity_y \, d\velocity_z$, or
\begin{equation}
    f(\vec\velocity)d^3\vec\velocity = \frac{2}{\pi} \cdot \left(\frac{\mass}{2\BoltzmannConstant\temperature}\right)^2 \cdot \velocity \sin\sphericalCoordinateElevation \cdot \exp\left( -\frac{\mass\velocity^2}{2\BoltzmannConstant\temperature}\right) d^3\vec\velocity,
    \label{eq:mbfd_spherical}
\end{equation}
in spherical coordinates with $d^3\vec\velocity = \velocity^2 \cos\sphericalCoordinateElevation \, d\velocity \, d\sphericalCoordinateElevation \, d\sphericalCoordinateAzimuth$ [@Brinkmann1970; @Armand1977; @Smith1978; @Schoerghofer2022].


{{< include velocity_distributions/boxes/_mbfd_components.qmd >}}


Through integration over the solid angles of Eq. \eqref{eq:mbfd_spherical}, the [MBFD](/documentation/acronyms.qmd) speed distribution emerges as
\begin{equation}
    f(\velocity)d\velocity =  2 \cdot \left(\frac{\mass}{2\BoltzmannConstant\temperature}\right)^2 \cdot \velocity^3 \cdot \exp\left( -\frac{\mass\velocity^2}{2\BoltzmannConstant\temperature}\right) d\velocity.
    \label{eq:mbfd_speed}
\end{equation}
Note that the scaling factor $2$ is a result from the integration over half the sphere through $\sphericalCoordinateElevation\in\left(0,\pi/2\right)$. As before, this speed distribution can be analyzed to extract some typical speeds from it.


{{< include /img/documentation/fundamentals/velocity_distributions/mbfd/_mbfd.qmd >}}


@fig-mbfd shows the probability densities of three [MBFD](/documentation/acronyms.qmd) distributed, normalized velocities. The normalization of the velocities has been performed with $\sqrt{\mass/\BoltzmannConstant\temperature} = 1$. The <tt>1D-MBFD</tt> curve is showing the [pdf](/documentation/acronyms.qmd) of a velocity component perpendicular to the flux direction, which is equal to one-dimensional [MBD](/documentation/acronyms.qmd) velocities, see Eq. \eqref{eq:mbd_1d}, which in fact is equal to the scaled normal distribution $\mathcal{N}(0, \BoltzmannConstant\temperature/\mass)$. The second graph, <tt>1D-MBFD, flux</tt> shows the distribution of a directed velocity component in flux direction, $f_\parallel(\velocity)$, which is equal to
\begin{equation}
    f_\parallel (\velocity) d\velocity = 2\velocity \left(\frac{\mass}{2\BoltzmannConstant\temperature}\right) \cdot \exp\left(-\frac{\mass\velocity^2}{2\BoltzmannConstant\temperature}\right) d\velocity.
    \label{eq:mbfd_1d_parallel}
\end{equation}
Last, the graph <tt>3D-MBFD, speed</tt> shows the distribution of speeds of the three-dimensional form, given in Eq. \eqref{eq:mbfd_speed}. For the latter, the three typical speeds, the most probable speed $\velocity_p$, the mean speed $\meanof{\velocity}$ or the expected speed, and the root mean squared speed $\velocity_\text{rms}$, which are derived in the following. Note that, contrary to the [MBD](/documentation/acronyms.qmd), the root mean squared speed is lower than the other two typical speeds, due to its additional speed dependency, which is shifting the entire distribution to higher values and, thus, to $f(\velocity \approx 0.0) \approx 0.0$.


## Typical Speeds

The most probable speed occurs at the maximum likelihood of the Eq. \eqref{eq:mbfd_speed}:
\begin{equation}
    \left. \frac{df(\velocity)}{d\velocity}\right|_{\velocity_p} = 0 \qquad \Rightarrow \qquad \velocity_p = \sqrt{\frac{3\BoltzmannConstant\temperature}{\mass}}.
    \label{eq:mbfd_most_probable_speed}
\end{equation}


The expected value of the speed distribution, the mean speed $\meanof{\velocity}$ is calculated by using the ensemble average equation, shown in Eq. \eqref{eq:ensemble_average}:
\begin{equation}
    \meanof{\velocity} = \int_0^\infty \velocity f(\velocity) d\velocity = \sqrt{\frac{9\pi\BoltzmannConstant\temperature}{8\mass}} = \sqrt{\frac{3\pi}{8}} \,\cdot \velocity_p.
    \label{eq:mbfd_mean_speed}
\end{equation}


Lastly, the \gls{rms} speed is calculated as
\begin{equation}
    \velocity_\text{rms} = \sqrt{\meanof{\velocity^2}} = \left( \int_0^\infty \velocity^2 f(\velocity)d\velocity\right)^{1/2} = \sqrt{\frac{2\BoltzmannConstant\temperature}{\mass}} = \sqrt{\frac{2}{3}}\,\cdot \velocity_p.
    \label{eq:mbfd_rms_speed}
\end{equation}


{{< include velocity_distributions/boxes/_mbfd_typical_speeds.qmd >}}


{{< include velocity_distributions/tables/mbfd_typical_speeds/_mbfd_typical_speeds.qmd >}}


@tbl-mbfd_typical_speeds shows an overview of the speeds of the [MBFD](/documentation/acronyms.qmd) and their relation to the typical speeds. The $\velocity_{XX}$ denotes the speed at which the [cdf](/documentation/acronyms.qmd) evaluated to $F(\velocity_{XX}) = \int_0^{\velocity_{XX}} f(\velocity) d\velocity= XX\si{\percent}$. The entries are sorted by their [cdf](/documentation/acronyms.qmd) with the typical speeds highlighted and placed at the correct position. Note that $\velocity_{50}$ denotes the median of the distribution, which is not equal to the expected value $\meanof{\velocity}$. 


## Numerical Sampling

Let $\vec\Velocity$ be the random variable of the [MBFD](/documentation/acronyms.qmd) velocity, then any realization can be drawn from the respective [pdf](/documentation/acronyms.qmd):
\begin{equation}
    \vec\Velocity \sim f(\vec\velocity) = \frac{2}{\pi} \cdot \left(\frac{\mass}{2\BoltzmannConstant\temperature}\right)^2 \cdot \velocity_z \cdot \exp\left( -\frac{\mass\velocity^2}{2\BoltzmannConstant\temperature}\right)
\end{equation}
given in cartesian coordinates, see Eq. \eqref{eq:mbfd} and Eq. \eqref{eq:mbfd_spherical} for the function in spherical coordinates. Similar to the [MBD](/documentation/acronyms.qmd), the numerical sampling of the random variable can be performed by mapping each random component to one implemented numerical distribution. As a reminder, the most basic numerical distributions are the uniform distribution with random variable $R_u\in\left[0,1\right]$ with realization $r_u$ of $R_u\sim f(r_u)=1$ and a normal distribution with random variable $R_n\in\left(-\infty, \infty\right)$ with realization $r_n$ of $R_n\sim f(r_n) = \mathcal{N}\left(r_n | 0, 1 \right)$ with zero mean and unit variance.


In cartesian coordinates, with $\vec\Velocity = \left(\Velocity_x, \Velocity_y, \Velocity_z\right)$, three first two directions are assumed to be perpendicular to the flux, while the z-direction is parallel to the flux. Thus, both the x- and the y-component, $\velocity_x$ and $\velocity_y$, can be numerically sampled like in the [MBD](/documentation/acronyms.qmd), which is with scaled normal distributions, see Eqs. \eqref{eq:mbd_random_cartesian_component_2}, \eqref{eq:mbd_random_cartesian_component}. The flux direction is drawing from the $f_\parallel$ [pdf](/documentation/acronyms.qmd), see Eq. \eqref{eq:mbfd_1d_parallel}, which can not directly translated in either a uniform or a normal distribution. Therefor, the respective [cdf](/documentation/acronyms.qmd), $F_\parallel\left(\velocity_z\right)$,  must be matched with the uniform [cdf](/documentation/acronyms.qmd):
\begin{align}
    r_{\velocity_z} &= \int_0^{r_{\velocity_z}} f(r_u) dr_u = \int_0^{\velocity_z} f_\parallel(\velocity) d\velocity = F_\parallel\left(\velocity_z\right) = 1 - \exp\left(-\frac{\mass\velocity_z^2}{2\BoltzmannConstant\temperature}\right) \\
    \Rightarrow\qquad \velocity_z &= \sqrt{-\ln\left(1-r_{\velocity_z}\right)\frac{2\BoltzmannConstant\temperature}{\mass}}.
    \label{eq:mbfd_random_cartesian_component}
\end{align}


$\vec\Velocity$ can also be expressed in spherical coordinates as $\vec\Velocity=\left(\Velocity_\velocity, \Velocity_\sphericalCoordinateElevation, \Velocity_\sphericalCoordinateAzimuth \right)$ with the differential $d^3\vec\velocity=\velocity^2 \, \cos\sphericalCoordinateElevation \, d\velocity d\sphericalCoordinateElevation d\sphericalCoordinateAzimuth$. The additional terms are distributed to the respective random variable:
\begin{alignat}{3}
    \Velocity_\velocity &\sim f(\velocity) && \qquad\text{with realization }\velocity, \\    
    \Velocity_\sphericalCoordinateElevation &\sim f(\sphericalCoordinateElevation) = 2\sin\sphericalCoordinateElevation\cos\sphericalCoordinateElevation && \qquad\text{with realization }\sphericalCoordinateElevation, \text{ and } \\    
    \Velocity_\sphericalCoordinateAzimuth &\sim f(\sphericalCoordinateAzimuth) = \frac{1}{2\pi} && \qquad\text{with realization }\sphericalCoordinateAzimuth.
\end{alignat}
As before, the [cdf](/documentation/acronyms.qmd) of the random variables can be set to equal the [cdf](/documentation/acronyms.qmd) of the unit uniform distribution:
\begin{alignat}{3}
    r_\velocity &= \int_0^{r_\velocity} f(r_u) dr_u = \int_0^\velocity f(\tilde\velocity)d\tilde\velocity, \\
    r_\sphericalCoordinateElevation &= \int_0^{r_\sphericalCoordinateElevation} f(r_u) dr_u = \int_0^\sphericalCoordinateElevation f(\tilde\sphericalCoordinateElevation)d\tilde\sphericalCoordinateElevation &&= 1 - \cos^2\sphericalCoordinateElevation, \\
    r_\sphericalCoordinateAzimuth &= \int_0^{r_\sphericalCoordinateAzimuth} f(r_u) dr_u = \int_{-\pi}^\sphericalCoordinateAzimuth f(\tilde\sphericalCoordinateAzimuth)d\tilde\sphericalCoordinateAzimuth &&= \frac{\sphericalCoordinateAzimuth+\pi}{2\pi}.
\end{alignat}
While the latter two integrals are trivial, leading to a cosine-squared dependence of the elevation angle $\sphericalCoordinateElevation$ and a uniform dependence on the azimuth angle $\sphericalCoordinateAzimuth$, the speed integral evaluates to
\begin{equation}
    r_\velocity = 1 - \exp \left( -\frac{\mass\velocity^2}{2\BoltzmannConstant\temperature} \right) \cdot \left( \frac{\mass\velocity^2}{2\BoltzmannConstant\temperature} + 1\right).
    \label{eq:mbfd_random_speed}
\end{equation}
only $\sphericalCoordinateElevation=\cos^{-1}\left(1-r_\sphericalCoordinateElevation\right)$ and $\sphericalCoordinateAzimuth = 2\pi r_\sphericalCoordinateAzimuth - \pi$ can both be directly calculated from their respective realization of the uniform unit random variable, as there is no direct inversion of Eq. \eqref{eq:mbfd_random_speed}.


{{< include velocity_distributions/apirefs/_mbfd.qmd >}}

