For purely ballistic trajectories, the landing position of a particle can be analytically calculated.

<!-- {{< include ballistic_trajectories/_orbital_mechanics_functions.qmd >}} -->


## General Solution

[{{< bi code >}} [`landing_position`](/api/exospheres/landing_position.qmd)]{.aside}

The following equations, mostly based on orbital mechanics functions presented in @Kegerreis2017, @Walter2018, and @Schoerghofer2022a, assume a perfectly spherical central body with radius $\radius$ and of mass $\mass$. Based on the launch velocity vector $\vec\velocity\in\Set{R}^3$ at the launch position $\left(\longitude_0, \latitude_0\right)$, the landing coordinates $\left(\longitude_1, \latitude_1\right)$ of the ballistic trajectory can be calculated using spherical trigonometry. The velocity vector is assumed to be in local cartesian coordinates, i.e. with $\velocity_1$ and $\velocity_2$ being the components in the horizontal plane and $\velocity_3$ being the vertical component. Starting with the escape velocity
\begin{equation}
  \velocity_{esc}\left(\radius, \mass\right) = \sqrt{\frac{2 \GravitationalConstant \mass}{\radius}} \label{eq:escape_velocity}
\end{equation}
the relative kinetic energy fraction
\begin{equation}
  \relativeKineticEnergy\left(\vec\velocity, \velocity_{esc}\right) = \left(\frac{|\vec\velocity|}{\velocity_{esc}}\right)^2  \label{eq:relative_kinetic_energy}
\end{equation}
can be determined. From the known launch velocity vector, the azimuth angle
\begin{equation}
  \azimuth\left(\vec\velocity \right) = \begin{cases}
      \cos^{-1}\left(\velocity_1/\sqrt{\velocity_1^2 + \velocity_2^2}\right) & \text{for } \velocity_2\geq0\\
      -\cos^{-1}\left(\velocity_1/\sqrt{\velocity_1^2 + \velocity_2^2}\right) & \text{for } \velocity_2<0
    \end{cases} \label{eq:azimuth_angle}
\end{equation}
and the zenith angle
\begin{equation}
  \zenith\left(\vec\velocity\right) = \tan^{-1}\left(\frac{\sqrt{\velocity_1^2 + \velocity_2^2}}{\velocity_3}\right)  \label{eq:zenith_angle} 
\end{equation}
can be extracted. The latter is subsequently used for the determination of the eccentricity
\begin{equation}
  \eccentricity\left(\relativeKineticEnergy, \zenith\right) = \sqrt{1 - 4 \relativeKineticEnergy \cdot (1 - \relativeKineticEnergy) \cdot \sin^2 \zenith}.  \label{eq:eccentricity}
\end{equation} 
With both the $\eccentricity$ and the relative kinetic energy $\relativeKineticEnergy$ known, the true anomaly at launch
\begin{equation}
  \trueAnomaly_0 = \trueAnomaly\left(\eccentricity, \relativeKineticEnergy\right) = \cos^{-1}\left(\frac{1}{\eccentricity} \cdot \left(\frac{1 - \eccentricity^2}{2-2 \relativeKineticEnergy} -1 \right)\right)  \label{eq:true_anomaly}
\end{equation}
as well as the landing position $\trueAnomaly_1 = 2\pi - \trueAnomaly_0$, can be calculated, leading to the angular difference between the landing and launch true anomaly $\trueAnomaly_1 - \trueAnomaly_0 = 2\pi - 2\trueAnomaly = \Delta\trueAnomaly$.


{{< include ballistic_trajectories/imgs/landing_position_calc/_landing_position_calc.qmd >}}


Based on @Butler1997, @Kegerreis2020, and @Schoerghofer2022a, the landing position $\left(\longitude_1, \latitude_1\right)$ can now be calculated using the launch position $\left(\longitude_0, \latitude_0\right)$, the traveled true anomaly $\Delta\trueAnomaly$, and the azimuth angle $\azimuth$ of the launch velocity. The problem is sketched in @fig-landing_position_calc, where $\overline{\latitude_0}$ and $\overline{\latitude_1}$ are the complementary angles of the latitudes, i.e., $\latitude = \frac{\pi}{2} - \overline{\latitude}$. Based on the cosine-law of spherical trigonometry, the angular triangle $\left(\Delta\trueAnomaly, \overline{\latitude_0}, \overline{\latitude_1}\right)$ can be used to find
\begin{equation}
    \sin\latitude_1 = \sin\latitude_0 \cdot \cos\Delta\trueAnomaly + \cos\latitude_0 \cdot \sin\Delta\trueAnomaly \cdot \sin\azimuth
\end{equation}
with $\cos\overline\latitude = \sin\latitude$ and $\sin\overline\latitude = \cos\latitude$, and the same triangle can be used for the calculation of the longitude difference $\Delta\longitude$ using the cosine-law
\begin{align}
    \cos\Delta\trueAnomaly &= \sin\latitude_0 \cdot \sin\latitude_1 + \cos\latitude_0 \cdot \cos\latitude_1 \cdot \cos\Delta\longitude \\[3mm]
    \Rightarrow\quad \cos\Delta\longitude &= \frac{\cos\Delta\trueAnomaly - \sin\latitude_0 \cdot \sin\latitude_1}{\cos\latitude_0 \cdot \cos\latitude_1}.
\end{align}
Note that numerical round-off issues could lead to sine and cosine expressions larger than one. What previous authors did not account for is that due to the periodicity of the cosine, two different cases have to be considered when extracting the $\Delta\longitude$:
\begin{equation}
    \Delta\longitude = \begin{cases} \Delta\longitude & \text{if } \Delta\trueAnomaly \leq \pi, \\ 2\pi - \Delta\longitude & \text{else.} \end{cases}
\end{equation}
Finally, the landing longitude $\longitude_1$ can be calculated based on the direction of the launch velocity as
\begin{equation}
    \Rightarrow \longitude_1 = \longitude_0 + \sgn\left(\velocity_1\right)\cdot\Delta\longitude,
\end{equation}
with the signum function $\sgn\left(\velocity_1\right) = 1$ for $\velocity_1\geq0$ and $\sgn\left(\velocity_1\right) = -1$ for $\velocity_1<0$.


## Time of Flight Calculation

The time of flight
\begin{equation}
  \flightTime = \Time_1 - \Time_0 = \period - 2\Time_0 \label{eq:time_of_flight}
\end{equation}
is the time difference between landing, $\Time_1$, and launching, $\Time_0$. Due to symmetry reasons, the landing time is $\Time_1 = \period-\Time_0$, and the expression of Eq. \eqref{eq:time_of_flight} can be simplified by using the orbital period
\begin{equation}
  \period\left(\semiMajorAxis, \mass\right) = 2\pi\sqrt{\frac{\semiMajorAxis^3}{\GravitationalConstant \mass}},  \label{eq:orbit_period}
\end{equation}
which requires the mass $\mass$ of the central body, as well as the semi-major axis of the trajectory's orbit
\begin{equation}
  \semiMajorAxis\left(\radius, \relativeKineticEnergy\right) = \frac{\radius}{2 \cdot \left(1 - \relativeKineticEnergy \right)}. \label{eq:semi_major_axis}
\end{equation}
The time at launch, $\Time_0$, can be calculated according to
\begin{equation}
  \Time\left(\meanAnomaly, \period\right) = \frac{\meanAnomaly}{2\pi} \cdot \period  \label{eq:orbit_time}
\end{equation}
with the mean anomaly at launch
\begin{equation}
  \meanAnomaly\left(\eccentricity, \eccentricAnomaly\right) = \eccentricAnomaly - \eccentricity\sin \eccentricAnomaly  \label{eq:mean_anomaly}
\end{equation}
and the eccentric anomaly at launch
\begin{equation}
  \eccentricAnomaly\left(\eccentricity, \trueAnomaly\right) = \begin{cases}
        2 \tan^{-1}\left( \sqrt{\frac{1-\eccentricity}{1+\eccentricity}} \cdot \tan\left(\frac{\trueAnomaly}{2}\right) \right) & \text{for } 0\leq\trueAnomaly<\pi\\
        2 \tan^{-1}\left( \sqrt{\frac{1-\eccentricity}{1+\eccentricity}} \cdot \tan\left(\frac{\trueAnomaly}{2}\right) \right) + 2\pi & \text{for } \pi\leq\trueAnomaly<2\pi
    \end{cases}  \label{eq:eccentric_anomaly}
\end{equation}
which are based on the previously calculated eccentricity, see Eq. \eqref{eq:eccentricity}, and true anomaly at launch, see Eq. \eqref{eq:true_anomaly}.







## Simplification for Uniform Gravity

Particles launched with small velocities do not reach altitudes at which the gravitational acceleration changes significantly.