The functions below derive various orbital parameters, such as the eccentricity, the semi-major axis, or the true anomaly, from the given input parameters, used for the spherical, two-dimensional trajectory calculation [@Walter2018; @Schoerghofer2022a]. While there are multiple ways of rewriting these equations, for example, by simply inserting the definition of one of the input parameters into the equation, the primary inputs necessary to solve these functions are the current velocity vector $\vec\velocity\in\Set{R}^3$, the mass of the planetary object $\mass\in\Set{R}^+$, and the current radial position $\radius\in\Set{R}^+$. Note that the velocity vector has to be provided in a [local cartesian coordinate system](/documentation/fundamentals/coordinate_systems.qmd) with $\velocity_1$ and $\velocity_2$ being the components in the horizontal plane and $\velocity_3$ being the vertical component. The physical parameters are usually defined for all or all positive real numbers, $\Set{R}$ or $\Set{R}^+$, with the exception of the azimuth and zenith angle, $\azimuthAngle, \zenithAngle\in\left[-\pi, \pi\right)$, and the true anomaly, eccentric anomaly, and mean anomaly, $\trueAnomaly, \eccentricAnomaly, \meanAnomaly\in\left[0, 2\pi\right)$, respectively.



Every function below can be solved analytically, except for Eq. \eqref{eq:eccentric_anomaly_e_M}. This equation is the iterative solution of Kepler's equation, based on the definition of the mean anomaly, see Eq. \eqref{eq:mean_anomaly_e_E}. Nonetheless, one can solve for the eccentric anomaly numerically using stationary iterative methods. The starting point $\eccentricAnomaly_0=\meanAnomaly$ given in the Table could also be substituted with $\eccentricAnomaly_0=0$, where $\eccentricAnomaly_1=\meanAnomaly$ leads to the same numerical solution after just one more iteration step.



## Azimuth Angle -- $\azimuthAngle$ {#sec-azimuth-angle}
The azimuth angle $\azimuthAngle$, measured mathematically positive from $\cartesianCoordinateX$, i.e., north from true east, can be calculated using the following multi-case definition:
\begin{equation}
    \azimuthAngle\left(\vec\velocity \right) = \begin{cases}
        \cos^{-1}\left(\velocity_1/\sqrt{\velocity_1^2 + \velocity_2^2}\right) & \text{for } \velocity_2\geq0\\
        -\cos^{-1}\left(\velocity_1/\sqrt{\velocity_1^2 + \velocity_2^2}\right) & \text{for } \velocity_2<0
    \end{cases} \label{eq:azimuth_angle_v}
\end{equation}
with a [local cartesian](/documentation/fundamentals/coordinate_systems.qmd) velocity vector $\vec\velocity = \left[\velocity_1, \velocity_2, \velocity_3\right]^T$. The equation can be rewritten as a single-case equation, avoiding the inverse cosine expression:
\begin{equation}
    \cos\azimuthAngle = \frac{\velocity_1}{\sqrt{\velocity_1^2+\velocity_2^2}}.
\end{equation} 
[{{< bi code >}} [`azimuth_angle_v`](/api/exospheres/orbital_mechanics.qmd): $\azimuthAngle\left(\vec\velocity\right)$: Eq. \eqref{eq:azimuth_angle_v}]{.aside}




## Eccentric Anomaly -- $\eccentricAnomaly$ {#sec-eccentric-anomaly}
The eccentric anomaly $\eccentricAnomaly$ has two distinctly different definitions, depending on the input parameters. The first, shown in Eq. \eqref{eq:eccentric_anomaly_e_theta}, is based on a given eccentricity $\eccentricity$ and true anomaly $\trueAnomaly$, while the second one, shown in Eq. \eqref{eq:eccentric_anomaly_e_M}, is a iterative approach on solving for the eccentric anomaly based on the mean anomaly $\meanAnomaly$ and eccentricity $\eccentricity$. 
\begin{align}
    \eccentricAnomaly\left(\eccentricity, \trueAnomaly\right) &= \begin{cases}
        2 \tan^{-1}\left( \sqrt{\frac{1-\eccentricity}{1+\eccentricity}} \cdot \tan\left(\frac{\trueAnomaly}{2}\right) \right) & \text{for } 0\leq\trueAnomaly<\pi\\
        2 \tan^{-1}\left( \sqrt{\frac{1-\eccentricity}{1+\eccentricity}} \cdot \tan\left(\frac{\trueAnomaly}{2}\right) \right) + 2\pi & \text{for } \pi\leq\trueAnomaly<2\pi
    \end{cases}  \label{eq:eccentric_anomaly_e_theta} \\[3mm]
     \eccentricAnomaly_{i+1}\left(\eccentricity, \meanAnomaly, \eccentricAnomaly_i\right) &= \meanAnomaly + \eccentricity\sin \eccentricAnomaly_i \quad\text{ with }\quad \eccentricAnomaly_0 = \meanAnomaly  \label{eq:eccentric_anomaly_e_M}
\end{align}
Similar to the azimuth angle before, Eq. \eqref{eq:eccentric_anomaly_e_theta} can be rewritten as a single-case equation, avoiding the inverse tangent expression:
\begin{equation}
    \tan\left(\eccentricAnomaly/2\right) = \sqrt{\frac{1-\eccentricity}{1+\eccentricity}} \cdot \tan\left(\trueAnomaly/2\right).
\end{equation}
[{{< bi code >}} [`eccentric_anomaly_e_theta`](/api/exospheres/orbital_mechanics.qmd): $\eccentricAnomaly\left(\eccentricity, \trueAnomaly\right)$: Eq. \eqref{eq:eccentric_anomaly_e_theta} </br> {{< bi code >}} [`eccentric_anomaly_e_M`](/api/exospheres/orbital_mechanics.qmd): $\eccentricAnomaly\left(\eccentricity, \meanAnomaly\right)$: Eq. \eqref{eq:eccentric_anomaly_e_M}]{.aside}




## Eccentricity -- $\eccentricity$ {#sec-eccentricity}
The eccentricity $\eccentricity$ 
\begin{align}
    \eccentricity\left(\relativeKineticEnergy, \zenithAngle\right) &= \sqrt{1 - 4 \relativeKineticEnergy \cdot (1 - \relativeKineticEnergy) \cdot \sin^2 \zenithAngle}  \label{eq:eccentricity_epskin_psi} \\
    \eccentricity\left(\semiMajorAxis, \semiLatusRectum\right) &= \sqrt{1 - \frac{\semiLatusRectum}{\semiMajorAxis}}  \label{eq:eccentricity_a_p} \\
    \eccentricity\left(\radius, \semiLatusRectum, \trueAnomaly\right) &= \frac{1}{\cos\trueAnomaly}\cdot\left(\frac{\semiLatusRectum}{\radius} - 1\right)  \label{eq:eccentricity_r_p_theta} \\
    \eccentricity\left(\eccentricAnomaly, \meanAnomaly\right) &= \frac{\eccentricAnomaly - \meanAnomaly}{\sin \eccentricAnomaly}  \label{eq:eccentricity_E_M}
\end{align}

::: {.column-margin}
{{< bi code >}} [`eccentricity_epskin_psi`](/api/exospheres/orbital_mechanics.qmd): $\eccentricity\left(\relativeKineticEnergy, \zenithAngle\right)$: Eq. \eqref{eq:eccentricity_epskin_psi}  

{{< bi code >}} [`eccentricity_epskin_v`](/api/exospheres/orbital_mechanics.qmd): $\eccentricity\left(\relativeKineticEnergy, \vec\velocity\right)$: Eq. \eqref{eq:eccentricity_epskin_psi} with $\velocity=\velocity(\zenithAngle)$ from Eq. \eqref{eq:zenith_angle_v}

{{< bi code >}} [`eccentricity_r_m_v`](/api/exospheres/orbital_mechanics.qmd): $\eccentricity\left(\radius, \mass, \velocity\right)$: Eq. \eqref{eq:eccentricity_epskin_psi} with $\relativeKineticEnergy=\relativeKineticEnergy\left(\velocity_{esc}(\radius,\mass),\velocity\right)$ from Eqs. \eqref{eq:escape_velocity_r_m} and \eqref{eq:relative_Ekin_v_vesc}, and with $\velocity=\velocity(\zenithAngle)$ from Eq. \eqref{eq:zenith_angle_v}
:::



## Escape Velocity -- $\velocity_{esc}$ {#sec-escape-velocity}
\begin{equation}
    \velocity_{esc}\left(\radius, \mass\right) = \sqrt{\frac{2 \GravitationalConstant \mass}{\radius}} \label{eq:escape_velocity_r_m}
\end{equation}

::: {.column-margin}
{{< bi code >}}  [`escape_velocity_r_m`](/api/exospheres/orbital_mechanics.qmd): $\velocity_{esc}\left(\radius, \mass\right)$: Eq. \eqref{eq:escape_velocity_r_m} 
:::



## Ground Track Distance -- $\distance$ {#sec-ground-track-distance}
\begin{equation}
    \distance\left(\radius, \Delta\trueAnomaly\right) = \radius \cdot \Delta\trueAnomaly  \label{eq:ground_track_distance_r_dtheta}
\end{equation}

::: {.column-margin}
{{< bi code >}} [`ground_distance_R_dtheta`](/api/exospheres/orbital_mechanics.qmd): $\distance\left(\radius, \trueAnomaly\right)$: Eq. \eqref{eq:ground_track_distance_r_dtheta}  

{{< bi code >}} [`ground_distance_R_a_e`](/api/exospheres/orbital_mechanics.qmd): $\distance\left(\radius, \semiMajorAxis, \eccentricity\right)$: Eq. \eqref{eq:ground_track_distance_r_dtheta} with $\Delta\trueAnomaly = 2\pi - 2\trueAnomaly$ and $\trueAnomaly = \trueAnomaly\left(\radius, \semiMajorAxis, \eccentricity\right)$ of Eq. \eqref{eq:true_anomaly_r_a_e}
:::




## Mean Anomaly  -- $\meanAnomaly$ {#sec-mean-anomaly}
\begin{equation}
    \meanAnomaly\left(\eccentricity, \eccentricAnomaly\right) = \eccentricAnomaly - \eccentricity\sin \eccentricAnomaly  \label{eq:mean_anomaly_e_E}
\end{equation}

::: {.column-margin}
{{< bi code >}} [`mean_anomaly_e_E`](/api/exospheres/orbital_mechanics.qmd): $\meanAnomaly\left(\eccentricity, \eccentricAnomaly\right)$: Eq. \eqref{eq:mean_anomaly_e_E}  

{{< bi code >}} [`mean_anomaly_e_theta`](/api/exospheres/orbital_mechanics.qmd): $\meanAnomaly\left(\eccentricity, \trueAnomaly\right)$: Eq. \eqref{eq:mean_anomaly_e_E} with $\eccentricAnomaly=\eccentricAnomaly(\eccentricity, \trueAnomaly)$ from Eq. \eqref{eq:eccentric_anomaly_e_theta}
:::




## Orbit Period -- $\period$ {#sec-orbit-period}
\begin{equation}
    \period\left(\semiMajorAxis, \mass\right) = 2\pi\sqrt{\frac{\semiMajorAxis^3}{\GravitationalConstant \mass}}  \label{eq:orbit_period_a_m}
\end{equation}

::: {.column-margin}
{{< bi code >}} [`orbit_period_a_m`](/api/exospheres/orbital_mechanics.qmd): $\period\left(\semiMajorAxis, \mass\right)$: Eq. \eqref{eq:orbit_period_a_m}  
:::




## Orbit Time -- $\Time$ {#sec-orbit-time}
\begin{equation}
    \Time\left(\meanAnomaly, \period\right) = \frac{\meanAnomaly}{2\pi} \cdot \period  \label{eq:orbit_time_M_P}
\end{equation}

::: {.column-margin}
{{< bi code >}} [`orbit_time_M_P`](/api/exospheres/orbital_mechanics.qmd): $\Time\left(\meanAnomaly, \period\right)$: Eq. \eqref{eq:orbit_time_M_P}  

{{< bi code >}} [`orbit_time_e_E_P`](/api/exospheres/orbital_mechanics.qmd): $\Time\left(\eccentricity, \eccentricAnomaly, \period\right)$: Eq. \eqref{eq:orbit_time_M_P} with $\meanAnomaly = \meanAnomaly(\eccentricity, \eccentricAnomaly)$ of Eq. \eqref{eq:mean_anomaly_e_E}

{{< bi code >}} [`orbit_time_e_theta_P`](/api/exospheres/orbital_mechanics.qmd): $\Time\left(\eccentricity, \trueAnomaly, \period\right)$: Eq. \eqref{eq:orbit_time_M_P} with $\meanAnomaly = \meanAnomaly(\eccentricity, \eccentricAnomaly)$ of Eq. \eqref{eq:mean_anomaly_e_E} and $\eccentricAnomaly = \eccentricAnomaly\left(\eccentricity, \trueAnomaly\right)$ of Eq. \eqref{eq:eccentric_anomaly_e_theta}
:::




## Relative Kinetic Energy -- $\relativeKineticEnergy$ {#sec-relative-kinetic-energy}
\begin{align}
    \relativeKineticEnergy\left(\vec\velocity, \velocity_{esc}\right) &= \left(\frac{|\vec\velocity|}{\velocity_{esc}}\right)^2  \label{eq:relative_Ekin_v_vesc} \\
    \relativeKineticEnergy\left(\radius, \semiMajorAxis\right) &= 1 - \frac{\radius}{2\semiMajorAxis}  \label{eq:relative_Ekin_r_a} \\
    \relativeKineticEnergy\left(\eccentricity, \trueAnomaly\right) &= 1 - \frac{1 - \eccentricity^2}{2 + 2\eccentricity\cos\left(\trueAnomaly\right)}  \label{eq:relative_Ekin_e_theta}
\end{align}

::: {.column-margin}
{{< bi code >}} [`epskin_vesc_v`](/api/exospheres/orbital_mechanics.qmd): $\relativeKineticEnergy\left(\vec\velocity, \velocity_{esc}\right)$: Eq. \eqref{eq:relative_Ekin_v_vesc}  

{{< bi code >}} [`epskin_r_m_v`](/api/exospheres/orbital_mechanics.qmd): $\relativeKineticEnergy\left(\radius, \mass, \vec\velocity\right)$: Eq. \eqref{eq:relative_Ekin_v_vesc} with $\velocity_{esc} = \velocity_{esc}\left(\radius, \mass\right)$ of Eq. \eqref{eq:escape_velocity_r_m}

{{< bi code >}} [`epskin_r_a`](/api/exospheres/orbital_mechanics.qmd): $\relativeKineticEnergy\left(\radius, \semiMajorAxis\right)$: Eq. \eqref{eq:relative_Ekin_r_a}

{{< bi code >}} [`epskin_e_theta`](/api/exospheres/orbital_mechanics.qmd): $\relativeKineticEnergy\left(\eccentricity, \trueAnomaly\right)$: Eq. \eqref{eq:relative_Ekin_e_theta}
:::




## Semi-Latus Rectum -- $\semiLatusRectum$ {#sec-semi-latus-rectum}
\begin{align}
    \semiLatusRectum\left(\semiMajorAxis, \eccentricity\right) &= \semiMajorAxis \cdot (1 - \eccentricity^2)  \label{eq:semi_latus_rectum_a_e} \\
    \semiLatusRectum\left(\radius, \eccentricity, \trueAnomaly\right) &= \radius \cdot \left(1 + \eccentricity \cdot \cos \trueAnomaly\right)  \label{eq:semi_latus_rectum_r_e_theta}
\end{align}

::: {.column-margin}
{{< bi code >}} [`semi_latus_rectum_a_e`](/api/exospheres/orbital_mechanics.qmd): $\semiLatusRectum\left(\semiMajorAxis, \eccentricity\right)$: Eq. \eqref{eq:semi_latus_rectum_a_e}  

{{< bi code >}} [`semi_latus_rectum_r_e_theta`](/api/exospheres/orbital_mechanics.qmd): $\semiLatusRectum\left(\radius, \eccentricity, \trueAnomaly\right)$: Eq. \eqref{eq:semi_latus_rectum_r_e_theta}  
:::




## Semi-Major Axis -- $\semiMajorAxis$ {#sec-semi-major-axis}
\begin{align}
    \semiMajorAxis\left(\radius, \relativeKineticEnergy\right) &= \frac{\radius}{2 \cdot \left(1 - \relativeKineticEnergy \right)}  \label{eq:semi_major_axis_r_epskin} \\
    \semiMajorAxis\left(\semiLatusRectum, \eccentricity\right) &= \frac{\semiLatusRectum}{1 - \eccentricity^2}  \label{eq:semi_major_axis_p_e}
\end{align}

::: {.column-margin}
{{< bi code >}} [`semi_major_axis_r_epskin`](/api/exospheres/orbital_mechanics.qmd): $\semiMajorAxis\left(\radius, \relativeKineticEnergy\right)$: Eq. \eqref{eq:semi_major_axis_r_epskin}  

{{< bi code >}} [`semi_major_axis_r_m_v`](/api/exospheres/orbital_mechanics.qmd): $\semiMajorAxis\left(\radius, \mass, \vec\velocity\right)$: Eq. \eqref{eq:semi_major_axis_r_epskin} with $\relativeKineticEnergy=\relativeKineticEnergy\left(\radius, \mass, \vec\velocity\right)$ and $\velocity_{esc}=\velocity_{esc}\left(\radius, \mass\right)$ of Eqs. \eqref{eq:relative_Ekin_v_vesc} and \eqref{eq:escape_velocity_r_m}

{{< bi code >}} [`semi_major_axis_p_e`](/api/exospheres/orbital_mechanics.qmd): $\semiMajorAxis\left(\semiLatusRectum, \eccentricity\right)$: Eq. \eqref{eq:semi_major_axis_p_e}  

{{< bi code >}} [`semi_major_axis_r_e_theta`](/api/exospheres/orbital_mechanics.qmd): $\semiMajorAxis\left(\radius, \eccentricity, \trueAnomaly\right)$: Eq. \eqref{eq:semi_major_axis_p_e} with $\semiLatusRectum=\semiLatusRectum\left(\radius, \eccentricity, \trueAnomaly\right)$ of Eq. \eqref{eq:semi_latus_rectum_r_e_theta}
:::



## True Anomaly -- $\trueAnomaly$ {#sec-true-anomaly}
\begin{align}
    \trueAnomaly\left(\radius, \semiMajorAxis, \eccentricity\right) &= \cos^{-1}\left(\frac{1}{\eccentricity} \cdot \left(\frac{\semiMajorAxis}{\radius} \left( 1 - \eccentricity^2 \right) -1 \right)\right)  \label{eq:true_anomaly_r_a_e} \\
    \trueAnomaly\left(\eccentricity, \relativeKineticEnergy\right) &= \cos^{-1}\left(\frac{1}{\eccentricity} \cdot \left(\frac{1 - \eccentricity^2}{2-2 \relativeKineticEnergy} -1 \right)\right)  \label{eq:true_anomaly_e_epskin}
\end{align}

::: {.column-margin}
{{< bi code >}} [`true_anomaly_r_a_e`](/api/exospheres/orbital_mechanics.qmd): $\trueAnomaly\left(\radius, \semiMajorAxis, \eccentricity\right)$: Eq. \eqref{eq:true_anomaly_r_a_e}  

{{< bi code >}} [`true_anomaly_e_epskin`](/api/exospheres/orbital_mechanics.qmd): $\trueAnomaly\left(\eccentricity, \relativeKineticEnergy\right)$: Eq. \eqref{eq:true_anomaly_e_epskin}  

{{< bi code >}} [`true_anomaly_epskin_v`](/api/exospheres/orbital_mechanics.qmd): $\trueAnomaly\left(\relativeKineticEnergy, \vec\velocity\right)$: Eq. \eqref{eq:true_anomaly_epskin_v}  
:::



## Zenith Angle -- $\zenithAngle$ {#sec-zenith-angle}
\begin{equation}
    \zenithAngle\left(\vec\velocity\right) = \tan^{-1}\left(\frac{\sqrt{\velocity_1^2 + \velocity_2^2}}{\velocity_3}\right)  \label{eq:zenith_angle_v}
\end{equation}

::: {.column-margin}
{{< bi code >}} [`zenith_angle_v`](/api/exospheres/orbital_mechanics.qmd): $\zenithAngle\left(\vec\velocity\right)$: Eq. \eqref{eq:zenith_angle_v}  
:::

