---
title: Acronyms
citation: false
---

{{< include /resources/latex/_defs.qmd >}}
{{< include /resources/latex/_symbols.qmd >}}

::: {.hidden }
# {{< meta title >}} {.unnumbered}
:::

::: {.panel-tabset}

# {{< bi table >}} Table

+-----------+---------------------------------------------------------------+
| ALSEP     | Apollo Lunar Surface Experiments Package                      |
+-----------+---------------------------------------------------------------+
| cdf       | cumulative distribution function                              |
|           |                                                               |
| CME       | Coronal Mass Ejection                                         |
+-----------+---------------------------------------------------------------+
| DLRE      | Diviner Lunar Radiometer Experiment                           |
+-----------+---------------------------------------------------------------+
| ENA       | Energetic Neutral Atoms                                       |
|           |                                                               |
| ESA       | European Space Agency                                         |
|           |                                                               |
| ESD       | Electron Stimulated Desorption                                |
+-----------+---------------------------------------------------------------+
| LACE      | Lunar Atmospheric Composition Experiment                      |
|           |                                                               |
| LADEE     | Lunar Atmosphere and Dust Environment Explorer                |              
|           |                                                               |
| LRO       | Lunar Reconnaissance Orbiter                                  |
|           |                                                               |
| LROC      | Lunar Reconnaissance Orbiter Camera                           |
+-----------+---------------------------------------------------------------+
| HEALPix   | Hierarchical Equal Area iso-Latitude Pixelization             |
+-----------+---------------------------------------------------------------+
| IID       | Independent and Identically Distributed                       |
|           |                                                               |
| IMF       | Interplanetary Magnetic Field                                 |
+-----------+---------------------------------------------------------------+
| MBD       | Maxwell-Boltzmann Distribution                                |
|           |                                                               |
| MBFD      | Maxwell-Boltzmann Flux Distribution                           |
|           |                                                               |
| MESSENGER | MErcury Surface, Space ENvironment, GEochemistry, and Ranging |
|           |                                                               |
| MMIV      | Micrometeoroid Impact Vaporization                            |
+-----------+---------------------------------------------------------------+
| NASA      | National Aeronautics and Space Administration                 |
|           |                                                               |
| NMS       | Neutral Mass Spectrometer                                     |
+-----------+---------------------------------------------------------------+
| pdf       | probability density function                                  |
|           |                                                               |
| PDS       | Planetary Data System                                         |
|           |                                                               |
| PSD       | Photon Stimulated Desorption                                  |
|           |                                                               |
| PSR       | Permanently Shadowed Region                                   |
+-----------+---------------------------------------------------------------+
| rms       | root mean squared                                             |
+-----------+---------------------------------------------------------------+
| SSE       | Selenocentric Solar Ecliptic                                  |
+-----------+---------------------------------------------------------------+
| TPD       | Temperature Program Desorption                                |
|           |                                                               |
| TUM       | Technical University of Munich                                |
+-----------+---------------------------------------------------------------+
| UVS       | Ultraviolet Spectrometer (Apollo 17)                          |
+-----------+---------------------------------------------------------------+
| WAC       | Wide Angle Camera (LROC)                                      |
+-----------+---------------------------------------------------------------+

: {.hover}


# {{< bi code >}} $\LaTeX$

```latex
\newacronym{ALSEP}{ALSEP}{Apollo Lunar Surface Experiments Package}

\newacronym{cdf}{cdf}{cumulative distribution function}
\newacronym{CME}{CME}{Coronal Mass Ejection}

\newacronym{DLRE}{DLRE}{Diviner Lunar Radiometer Experiment}

\newacronym{ENA}{ENA}{Energetic Neutral Atoms}
\newacronym{ESA}{ESA}{European Space Agency}
\newacronym{ESD}{ESD}{Electron Stimulated Desorption}

\newacronym{LACE}{LACE}{Lunar Atmospheric Composition Experiment}
\newacronym{LADEE}{LADEE}{Lunar Atmosphere and Dust Environment Explorer}
\newacronym{LRO}{LRO}{Lunar Reconnaissance Orbiter}
\newacronym{LROC}{LROC}{Lunar Reconnaissance Orbiter Camera}

\newacronym{HEALPix}{HEALPix}{Hierarchical Equal Area iso-Latitude Pixelization}

\newacronym{IID}{IID}{Independent and Identically Distributed}
\newacronym{IMF}{IMF}{Interplanetary Magnetic Field}

\newacronym{MBD}{MBD}{Maxwell-Boltzmann Distribution}
\newacronym{MBFD}{MBFD}{Maxwell-Boltzmann Flux Distribution}
\newacronym{MESSENGER}{MESSENGER}{MErcury Surface, Space ENvironment, GEochemistry, and Ranging}
\newacronym{MMIV}{MMIV}{Micrometeoroid Impact Vaporization}

\newacronym{NASA}{NASA}{National Aeronautis and Space Administration}
\newacronym{NMS}{NMS}{Neutral Mass Spectrometer}

\newacronym{pdf}{pdf}{probability density function}
\newacronym{PDS}{PDS}{Planetary Data System}
\newacronym{PSD}{PSD}{Photon Stimulated Desorption}
\newacronym{PSR}{PSR}{Permanently Shadowed Region}

\newacronym{rms}{rms}{root mean squared}

\newacronym{SSE}{SSE}{Selenocentric Solar Ecliptic}

\newacronym{TUM}{TUM}{Technical University of Munich}

\newacronym{UVS}{UVS}{Ultraviolet Spectrometer}

\newacronym{WAC}{WAC}{Wide Angle Camera}
```
:::




[ ]{.aside}