---
title: "Code"
---

---


The `ExESS` package is structured into four main parts, which are the four main folders in the `/src` directory:

## Repository Structure

```jl
ExESS/  
├─ data/  
├─ res/  
├─ src/  
│  ├─ base/  
│  ├─ exospheres/  
│  ├─ grids/  
│  ├─ surfaces/  
│  └─ ExESS.jl  
├─ test/  
├─ . . .  
└─ README.md  
```

## Source Files

### Base Functionalities -- `base/` 
`ExESS/src/base/` contains basic functionality that is used at multiple places in the code, e.g., physical constants, coordinate system definitions, utility functions, and some probability distributions.

* [`constants.jl`](/api/base/constants.qmd)  
* [`cs.jl`](/api/base/cs.qmd)
* [`distributions.jl`](/api/base/distributions.qmd)
* [`utils.jl`](/api/base/utility.qmd)

### Exospheres -- `exospheres/`
`ExESS/src/exospheres/` contains all scripts that define functions that have something to do with simulating the exosphere. Due to the assumption of surface-bounded exospheres, [Monte-Carlo methods](https://en.wikipedia.org/wiki/Monte_Carlo_method) are the preferred simulation tool as each individual particle of the exosphere can be simulated independently. Implemented functionalities are mostly based on ballistic trajectory calculations.

* [`orbital_mechanics.jl`](/api/exospheres/orbital_mechanics.qmd)
* [`trajectories.jl`]()
* [`utils.jl`]()

### Numerical Grids -- `grids/`
`ExESS/src/grids/` contains all numerical discretization methods used in this package. While most functions can be called with `AbstractVector` inputs, their main use is meant to be in conjunction with the previously defined custom coordinate systems.

* [`global_healpix_2d_grids.jl`]()  
* [`global_spiral_2d_grids.jl`]()  
* [`global_structured_2d_grids.jl`]()  
* [`global_structured_3d_grids.jl`]()  
* [`types.jl`]()  
* [`utils.jl`]()  

### Surfaces -- `surfaces/`
`ExESS/src/surfaces/` contains all functions that are used to calculate surface properties, e.g., surface temperatures, reaction kinetics, thermal conductivities, and diffusion coefficients.

* [`density.jl`]()  
* [`porosity.jl`]()  
* [`reaction_rates.jl`]()  
* [`regolith.jl`]()  
* [`temperature.jl`]()  
* [`thermal_conductivity_parzinger2014.jl`]()  
* [`utils.jl`]()  