---
title: "Fibonnacci Sequence"
author: 
  name: Alexander Smolka
  email: a.smolka@tum.de
  orcid: 0000-0002-4848-3473
  affiliation: Technical University of Munich
date: 17 07 2023
tbl-colwidths: [10,20,10,20,10,20]
---

---

## Problem

Write a Julia function that computes the last digit of the `n`-th [Fibonacci number](https://en.wikipedia.org/wiki/Fibonacci_sequence), and compute the last digit of the 10th, 100th, 1000th, and 10000th Fibonacci number.

**Additional Requirements**:

* The function's name shall be `fib_last_digit`.
* The Fibonacci sequence starts with `0` and `1`.
* The function should take only one argument called `n` of type `Integer`.
* The function should return an `Integer` between `0` and `9` (inclusive).
* The function should depend on **no** additional packages.
* The function shall be *fast*!


## Hints

::: {.callout-note collapse="true" appearance="simple"}
# How to get the last digit of a number?
You can use the `mod` function to compute the remainder of the division of two integers. For example, `mod(5, 2)` returns `1`. What would happen if you take the remainder of a number divided by `10`?
:::


## Solution

::: {.callout-note collapse="true" appearance="simple"}
# Values

::: {layout-ncol=3}

| `n` | `fib_last_digit(n)` |
|---|---|
| 1 | 0 |
| 2 | 1 |
| 3 | 1 |
| 4 | 2 |
| 5 | 3 |

: {.hover}

| `n` | `fib_last_digit(n)` |
|---|---|
| 6 | 5 |
| 7 | 8 |
| 8 | 3 |
| 9 | 1 |
| 10 | **4** |

: {.hover}

| `n` | `fib_last_digit(n)` |
|---|---|
| 100 | **6** |
| 1,000 | **6** |
| 10,000 | **6** |
| 100,000 | **6** |
| 1,000,000 | **6** |

: {.hover}

:::

:::

::: {.callout-note collapse="true" appearance="simple"}
# Follow-Up Question

Why are the last couple of entries all **6**? Is this pure coincidence or do the last digits of the Fibonacci sequence repeat? Use your function to find out!

:::